namespace winKCdrill2
{
	// Token: 0x0200000F RID: 15
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmTestDrill : global::System.Windows.Forms.Form
	{
		// Token: 0x06000296 RID: 662 RVA: 0x0003C894 File Offset: 0x0003AC94
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06000297 RID: 663 RVA: 0x0003C8B4 File Offset: 0x0003ACB4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.txtSekunder = new global::System.Windows.Forms.TextBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.txtNotes = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.txtArea = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtTotUt = new global::System.Windows.Forms.TextBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.txtStoppBvikt = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.txtStoppAvikt = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.txtStartBvikt = new global::System.Windows.Forms.TextBox();
			this.lblStartAVikt = new global::System.Windows.Forms.Label();
			this.txtStartAvikt = new global::System.Windows.Forms.TextBox();
			this.txtColNr = new global::System.Windows.Forms.TextBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.lblBinder = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.KnappF3 = new global::System.Windows.Forms.Button();
			this.KnappF2 = new global::System.Windows.Forms.Button();
			this.lblDriver = new global::System.Windows.Forms.Label();
			this.KnappF4 = new global::System.Windows.Forms.Button();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.KnappF1 = new global::System.Windows.Forms.Button();
			this.txtStign = new global::System.Windows.Forms.TextBox();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.lblClip = new global::System.Windows.Forms.Label();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.txtBindOut = new global::System.Windows.Forms.TextBox();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.txtToDepth = new global::System.Windows.Forms.TextBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.txtTeoLängd = new global::System.Windows.Forms.TextBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.lblNoCom = new global::System.Windows.Forms.Label();
			this.tmrInSignaler = new global::System.Windows.Forms.Timer(this.components);
			this.GroupBox5 = new global::System.Windows.Forms.GroupBox();
			this.tmrPelare = new global::System.Windows.Forms.Timer(this.components);
			this.DataGrid1 = new global::System.Windows.Forms.DataGrid();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.KnappF5 = new global::System.Windows.Forms.Button();
			this.lblDjup = new global::System.Windows.Forms.Label();
			this.lblTempKomp = new global::System.Windows.Forms.Label();
			this.lblFuktighet = new global::System.Windows.Forms.Label();
			this.lblTryckRör = new global::System.Windows.Forms.Label();
			this.PicUtA8 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA7 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA6 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA5 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt1 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsV = new global::System.Windows.Forms.PictureBox();
			this.PicInB1 = new global::System.Windows.Forms.PictureBox();
			this.KnappF10 = new global::System.Windows.Forms.Button();
			this.KnappF9 = new global::System.Windows.Forms.Button();
			this.KnappF8 = new global::System.Windows.Forms.Button();
			this.TimerCellmat = new global::System.Windows.Forms.Timer(this.components);
			this.lblTeoUt = new global::System.Windows.Forms.Label();
			this.KnappF7 = new global::System.Windows.Forms.Button();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.PicBorr = new global::System.Windows.Forms.PictureBox();
			this.lblMättUt = new global::System.Windows.Forms.Label();
			this.PicBlåsUt7 = new global::System.Windows.Forms.PictureBox();
			this.PicUtB1 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt6 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt5 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt4 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt3 = new global::System.Windows.Forms.PictureBox();
			this.PicBlåsUt2 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA4 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA3 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA2 = new global::System.Windows.Forms.PictureBox();
			this.PicUtA1 = new global::System.Windows.Forms.PictureBox();
			this.PicCompUt = new global::System.Windows.Forms.PictureBox();
			this.PicInA1 = new global::System.Windows.Forms.PictureBox();
			this.PicMark = new global::System.Windows.Forms.PictureBox();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.PictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.lblJunttan = new global::System.Windows.Forms.Label();
			this.Panel2 = new global::System.Windows.Forms.Panel();
			this.KnappF6 = new global::System.Windows.Forms.Button();
			this.lblInfoFst = new global::System.Windows.Forms.Label();
			this.txtDjupHåkan = new global::System.Windows.Forms.TextBox();
			this.SerieNovatron = new global::System.IO.Ports.SerialPort(this.components);
			this.GroupBox2.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGrid1).BeginInit();
			this.GroupBox3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsV).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicInB1).BeginInit();
			this.Panel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.PicBorr).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtB1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicCompUt).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicInA1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicMark).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.Panel2.SuspendLayout();
			this.SuspendLayout();
			global::System.Windows.Forms.Control label = this.Label10;
			global::System.Drawing.Point location = new global::System.Drawing.Point(272, 56);
			label.Location = location;
			this.Label10.Name = "Label10";
			this.Label10.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label2 = this.Label10;
			global::System.Drawing.Size size = new global::System.Drawing.Size(56, 24);
			label2.Size = size;
			this.Label10.TabIndex = 13;
			this.Label10.Text = "Time:";
			this.Label10.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtSekunder.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtSekunder.Enabled = false;
			this.txtSekunder.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtSekunder = this.txtSekunder;
			location = new global::System.Drawing.Point(336, 56);
			txtSekunder.Location = location;
			this.txtSekunder.Name = "txtSekunder";
			global::System.Windows.Forms.Control txtSekunder2 = this.txtSekunder;
			size = new global::System.Drawing.Size(48, 26);
			txtSekunder2.Size = size;
			this.txtSekunder.TabIndex = 12;
			this.txtSekunder.Text = "0";
			this.txtSekunder.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.Control label3 = this.Label3;
			location = new global::System.Drawing.Point(16, 56);
			label3.Location = location;
			this.Label3.Name = "Label3";
			this.Label3.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label4 = this.Label3;
			size = new global::System.Drawing.Size(104, 24);
			label4.Size = size;
			this.Label3.TabIndex = 3;
			this.Label3.Text = "Notes";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtNotes.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtNotes.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtNotes = this.txtNotes;
			location = new global::System.Drawing.Point(136, 56);
			txtNotes.Location = location;
			this.txtNotes.Name = "txtNotes";
			global::System.Windows.Forms.Control txtNotes2 = this.txtNotes;
			size = new global::System.Drawing.Size(248, 26);
			txtNotes2.Size = size;
			this.txtNotes.TabIndex = 2;
			this.txtNotes.Text = "No notes";
			global::System.Windows.Forms.Control label5 = this.Label11;
			location = new global::System.Drawing.Point(272, 24);
			label5.Location = location;
			this.Label11.Name = "Label11";
			this.Label11.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label6 = this.Label11;
			size = new global::System.Drawing.Size(56, 24);
			label6.Size = size;
			this.Label11.TabIndex = 11;
			this.Label11.Text = "Tot Out:";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtArea.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtArea.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtArea = this.txtArea;
			location = new global::System.Drawing.Point(136, 88);
			txtArea.Location = location;
			this.txtArea.Name = "txtArea";
			global::System.Windows.Forms.Control txtArea2 = this.txtArea;
			size = new global::System.Drawing.Size(216, 26);
			txtArea2.Size = size;
			this.txtArea.TabIndex = 4;
			this.txtArea.Text = "Site";
			global::System.Windows.Forms.Control label7 = this.Label1;
			location = new global::System.Drawing.Point(16, 24);
			label7.Location = location;
			this.Label1.Name = "Label1";
			this.Label1.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label8 = this.Label1;
			size = new global::System.Drawing.Size(104, 24);
			label8.Size = size;
			this.Label1.TabIndex = 1;
			this.Label1.Text = "Column number";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtTotUt.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtTotUt.Enabled = false;
			this.txtTotUt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtTotUt = this.txtTotUt;
			location = new global::System.Drawing.Point(336, 24);
			txtTotUt.Location = location;
			this.txtTotUt.Name = "txtTotUt";
			global::System.Windows.Forms.Control txtTotUt2 = this.txtTotUt;
			size = new global::System.Drawing.Size(48, 26);
			txtTotUt2.Size = size;
			this.txtTotUt.TabIndex = 10;
			this.txtTotUt.Text = "0";
			this.txtTotUt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.GroupBox2.Controls.Add(this.Label10);
			this.GroupBox2.Controls.Add(this.txtSekunder);
			this.GroupBox2.Controls.Add(this.Label11);
			this.GroupBox2.Controls.Add(this.txtTotUt);
			this.GroupBox2.Controls.Add(this.Label8);
			this.GroupBox2.Controls.Add(this.txtStoppBvikt);
			this.GroupBox2.Controls.Add(this.Label9);
			this.GroupBox2.Controls.Add(this.txtStoppAvikt);
			this.GroupBox2.Controls.Add(this.Label7);
			this.GroupBox2.Controls.Add(this.txtStartBvikt);
			this.GroupBox2.Controls.Add(this.lblStartAVikt);
			this.GroupBox2.Controls.Add(this.txtStartAvikt);
			this.GroupBox2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox = this.GroupBox2;
			location = new global::System.Drawing.Point(618, 402);
			groupBox.Location = location;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox2;
			size = new global::System.Drawing.Size(390, 104);
			groupBox2.Size = size;
			this.GroupBox2.TabIndex = 39;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "Last Column";
			global::System.Windows.Forms.Control label9 = this.Label8;
			location = new global::System.Drawing.Point(144, 55);
			label9.Location = location;
			this.Label8.Name = "Label8";
			this.Label8.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label10 = this.Label8;
			size = new global::System.Drawing.Size(56, 24);
			label10.Size = size;
			this.Label8.TabIndex = 9;
			this.Label8.Text = "Stop B:";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtStoppBvikt.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtStoppBvikt.Enabled = false;
			this.txtStoppBvikt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtStoppBvikt = this.txtStoppBvikt;
			location = new global::System.Drawing.Point(208, 55);
			txtStoppBvikt.Location = location;
			this.txtStoppBvikt.Name = "txtStoppBvikt";
			global::System.Windows.Forms.Control txtStoppBvikt2 = this.txtStoppBvikt;
			size = new global::System.Drawing.Size(48, 26);
			txtStoppBvikt2.Size = size;
			this.txtStoppBvikt.TabIndex = 8;
			this.txtStoppBvikt.Text = "0";
			this.txtStoppBvikt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.Control label11 = this.Label9;
			location = new global::System.Drawing.Point(144, 23);
			label11.Location = location;
			this.Label9.Name = "Label9";
			this.Label9.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label12 = this.Label9;
			size = new global::System.Drawing.Size(56, 24);
			label12.Size = size;
			this.Label9.TabIndex = 7;
			this.Label9.Text = "Stop A:";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtStoppAvikt.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtStoppAvikt.Enabled = false;
			this.txtStoppAvikt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtStoppAvikt = this.txtStoppAvikt;
			location = new global::System.Drawing.Point(208, 23);
			txtStoppAvikt.Location = location;
			this.txtStoppAvikt.Name = "txtStoppAvikt";
			global::System.Windows.Forms.Control txtStoppAvikt2 = this.txtStoppAvikt;
			size = new global::System.Drawing.Size(48, 26);
			txtStoppAvikt2.Size = size;
			this.txtStoppAvikt.TabIndex = 6;
			this.txtStoppAvikt.Text = "0";
			this.txtStoppAvikt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.Control label13 = this.Label7;
			location = new global::System.Drawing.Point(24, 56);
			label13.Location = location;
			this.Label7.Name = "Label7";
			this.Label7.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label14 = this.Label7;
			size = new global::System.Drawing.Size(56, 24);
			label14.Size = size;
			this.Label7.TabIndex = 5;
			this.Label7.Text = "Start B:";
			this.Label7.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtStartBvikt.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtStartBvikt.Enabled = false;
			this.txtStartBvikt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtStartBvikt = this.txtStartBvikt;
			location = new global::System.Drawing.Point(88, 56);
			txtStartBvikt.Location = location;
			this.txtStartBvikt.Name = "txtStartBvikt";
			global::System.Windows.Forms.Control txtStartBvikt2 = this.txtStartBvikt;
			size = new global::System.Drawing.Size(48, 26);
			txtStartBvikt2.Size = size;
			this.txtStartBvikt.TabIndex = 4;
			this.txtStartBvikt.Text = "0";
			this.txtStartBvikt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.Control lblStartAVikt = this.lblStartAVikt;
			location = new global::System.Drawing.Point(24, 24);
			lblStartAVikt.Location = location;
			this.lblStartAVikt.Name = "lblStartAVikt";
			this.lblStartAVikt.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control lblStartAVikt2 = this.lblStartAVikt;
			size = new global::System.Drawing.Size(56, 24);
			lblStartAVikt2.Size = size;
			this.lblStartAVikt.TabIndex = 3;
			this.lblStartAVikt.Text = "Start A:";
			this.lblStartAVikt.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtStartAvikt.BackColor = global::System.Drawing.SystemColors.HighlightText;
			this.txtStartAvikt.Enabled = false;
			this.txtStartAvikt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtStartAvikt = this.txtStartAvikt;
			location = new global::System.Drawing.Point(88, 24);
			txtStartAvikt.Location = location;
			this.txtStartAvikt.Name = "txtStartAvikt";
			global::System.Windows.Forms.Control txtStartAvikt2 = this.txtStartAvikt;
			size = new global::System.Drawing.Size(48, 26);
			txtStartAvikt2.Size = size;
			this.txtStartAvikt.TabIndex = 2;
			this.txtStartAvikt.Text = "0";
			this.txtStartAvikt.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtColNr.BackColor = global::System.Drawing.Color.FromArgb(192, 255, 192);
			this.txtColNr.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtColNr = this.txtColNr;
			location = new global::System.Drawing.Point(136, 24);
			txtColNr.Location = location;
			this.txtColNr.Name = "txtColNr";
			global::System.Windows.Forms.Control txtColNr2 = this.txtColNr;
			size = new global::System.Drawing.Size(168, 29);
			txtColNr2.Size = size;
			this.txtColNr.TabIndex = 0;
			this.txtColNr.Text = "Column no";
			global::System.Windows.Forms.Control label15 = this.Label5;
			location = new global::System.Drawing.Point(16, 152);
			label15.Location = location;
			this.Label5.Name = "Label5";
			this.Label5.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label16 = this.Label5;
			size = new global::System.Drawing.Size(104, 24);
			label16.Size = size;
			this.Label5.TabIndex = 9;
			this.Label5.Text = "Binder output";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control lblBinder = this.lblBinder;
			location = new global::System.Drawing.Point(136, 152);
			lblBinder.Location = location;
			this.lblBinder.Name = "lblBinder";
			global::System.Windows.Forms.Control lblBinder2 = this.lblBinder;
			size = new global::System.Drawing.Size(96, 24);
			lblBinder2.Size = size;
			this.lblBinder.TabIndex = 8;
			this.lblBinder.Text = "XX kg / m";
			this.lblBinder.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			global::System.Windows.Forms.Control label17 = this.Label6;
			location = new global::System.Drawing.Point(16, 120);
			label17.Location = location;
			this.Label6.Name = "Label6";
			this.Label6.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label18 = this.Label6;
			size = new global::System.Drawing.Size(104, 24);
			label18.Size = size;
			this.Label6.TabIndex = 7;
			this.Label6.Text = "Driver";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.KnappF3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF = this.KnappF3;
			location = new global::System.Drawing.Point(190, 0);
			knappF.Location = location;
			this.KnappF3.Name = "KnappF3";
			global::System.Windows.Forms.Control knappF2 = this.KnappF3;
			size = new global::System.Drawing.Size(92, 40);
			knappF2.Size = size;
			this.KnappF3.TabIndex = 2;
			this.KnappF3.TabStop = false;
			this.KnappF3.Text = "F3 =  Col.  Start";
			this.KnappF2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF3 = this.KnappF2;
			location = new global::System.Drawing.Point(90, 0);
			knappF3.Location = location;
			this.KnappF2.Name = "KnappF2";
			global::System.Windows.Forms.Control knappF4 = this.KnappF2;
			size = new global::System.Drawing.Size(92, 40);
			knappF4.Size = size;
			this.KnappF2.TabIndex = 1;
			this.KnappF2.TabStop = false;
			this.KnappF2.Text = "F2 =  Reset Auger Depth";
			global::System.Windows.Forms.Control lblDriver = this.lblDriver;
			location = new global::System.Drawing.Point(136, 120);
			lblDriver.Location = location;
			this.lblDriver.Name = "lblDriver";
			global::System.Windows.Forms.Control lblDriver2 = this.lblDriver;
			size = new global::System.Drawing.Size(192, 24);
			lblDriver2.Size = size;
			this.lblDriver.TabIndex = 6;
			this.lblDriver.Text = "Driver";
			this.lblDriver.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.KnappF4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF5 = this.KnappF4;
			location = new global::System.Drawing.Point(290, 0);
			knappF5.Location = location;
			this.KnappF4.Name = "KnappF4";
			global::System.Windows.Forms.Control knappF6 = this.KnappF4;
			size = new global::System.Drawing.Size(92, 40);
			knappF6.Size = size;
			this.KnappF4.TabIndex = 3;
			this.KnappF4.TabStop = false;
			this.KnappF4.Text = "F4 = Col. Stopp";
			global::System.Windows.Forms.Control label19 = this.Label4;
			location = new global::System.Drawing.Point(16, 88);
			label19.Location = location;
			this.Label4.Name = "Label4";
			this.Label4.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label20 = this.Label4;
			size = new global::System.Drawing.Size(104, 24);
			label20.Size = size;
			this.Label4.TabIndex = 5;
			this.Label4.Text = "Site";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.GroupBox1.Controls.Add(this.Label5);
			this.GroupBox1.Controls.Add(this.lblBinder);
			this.GroupBox1.Controls.Add(this.Label6);
			this.GroupBox1.Controls.Add(this.lblDriver);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.txtArea);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.txtNotes);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.txtColNr);
			this.GroupBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox1;
			location = new global::System.Drawing.Point(618, 506);
			groupBox3.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox1;
			size = new global::System.Drawing.Size(390, 190);
			groupBox4.Size = size;
			this.GroupBox1.TabIndex = 38;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Column Name and settings";
			this.KnappF1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF7 = this.KnappF1;
			location = new global::System.Drawing.Point(-10, 0);
			knappF7.Location = location;
			this.KnappF1.Name = "KnappF1";
			global::System.Windows.Forms.Control knappF8 = this.KnappF1;
			size = new global::System.Drawing.Size(92, 40);
			knappF8.Size = size;
			this.KnappF1.TabIndex = 0;
			this.KnappF1.TabStop = false;
			this.KnappF1.Text = "F1 = Show Instruments";
			this.txtStign.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.txtStign.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtStign = this.txtStign;
			location = new global::System.Drawing.Point(152, 24);
			txtStign.Location = location;
			this.txtStign.Name = "txtStign";
			global::System.Windows.Forms.Control txtStign2 = this.txtStign;
			size = new global::System.Drawing.Size(48, 29);
			txtStign2.Size = size;
			this.txtStign.TabIndex = 7;
			this.txtStign.Text = "0";
			this.txtStign.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.GroupBox4.Controls.Add(this.lblClip);
			this.GroupBox4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox4;
			location = new global::System.Drawing.Point(618, 90);
			groupBox5.Location = location;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox4;
			size = new global::System.Drawing.Size(197, 35);
			groupBox6.Size = size;
			this.GroupBox4.TabIndex = 41;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "GPS - Position of Drill";
			global::System.Windows.Forms.Control lblClip = this.lblClip;
			location = new global::System.Drawing.Point(21, 13);
			lblClip.Location = location;
			this.lblClip.Name = "lblClip";
			global::System.Windows.Forms.Control lblClip2 = this.lblClip;
			size = new global::System.Drawing.Size(136, 32);
			lblClip2.Size = size;
			this.lblClip.TabIndex = 0;
			this.lblClip.Text = "Nothing";
			this.lblClip.Visible = false;
			global::System.Windows.Forms.Control label21 = this.Label12;
			location = new global::System.Drawing.Point(24, 24);
			label21.Location = location;
			this.Label12.Name = "Label12";
			this.Label12.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label22 = this.Label12;
			size = new global::System.Drawing.Size(112, 24);
			label22.Size = size;
			this.Label12.TabIndex = 9;
			this.Label12.Text = "Up speed mm/r";
			this.Label12.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtBindOut.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.txtBindOut.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtBindOut = this.txtBindOut;
			location = new global::System.Drawing.Point(152, 56);
			txtBindOut.Location = location;
			this.txtBindOut.Name = "txtBindOut";
			global::System.Windows.Forms.Control txtBindOut2 = this.txtBindOut;
			size = new global::System.Drawing.Size(48, 29);
			txtBindOut2.Size = size;
			this.txtBindOut.TabIndex = 8;
			this.txtBindOut.Text = "0";
			this.txtBindOut.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.GroupBox6.Controls.Add(this.txtToDepth);
			this.GroupBox6.Controls.Add(this.Label14);
			this.GroupBox6.Controls.Add(this.Label15);
			this.GroupBox6.Controls.Add(this.txtTeoLängd);
			this.GroupBox6.Controls.Add(this.txtStign);
			this.GroupBox6.Controls.Add(this.Label12);
			this.GroupBox6.Controls.Add(this.Label13);
			this.GroupBox6.Controls.Add(this.txtBindOut);
			this.GroupBox6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox6;
			location = new global::System.Drawing.Point(618, 141);
			groupBox7.Location = location;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox6;
			size = new global::System.Drawing.Size(390, 101);
			groupBox8.Size = size;
			this.GroupBox6.TabIndex = 44;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "Column information";
			this.txtToDepth.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.txtToDepth.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtToDepth = this.txtToDepth;
			location = new global::System.Drawing.Point(324, 24);
			txtToDepth.Location = location;
			this.txtToDepth.Name = "txtToDepth";
			global::System.Windows.Forms.Control txtToDepth2 = this.txtToDepth;
			size = new global::System.Drawing.Size(58, 29);
			txtToDepth2.Size = size;
			this.txtToDepth.TabIndex = 11;
			this.txtToDepth.Text = "-21.00";
			this.txtToDepth.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtToDepth.Visible = false;
			global::System.Windows.Forms.Control label23 = this.Label14;
			location = new global::System.Drawing.Point(206, 24);
			label23.Location = location;
			this.Label14.Name = "Label14";
			this.Label14.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label24 = this.Label14;
			size = new global::System.Drawing.Size(112, 24);
			label24.Size = size;
			this.Label14.TabIndex = 13;
			this.Label14.Text = "To Depth";
			this.Label14.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label14.Visible = false;
			global::System.Windows.Forms.Control label25 = this.Label15;
			location = new global::System.Drawing.Point(222, 56);
			label25.Location = location;
			this.Label15.Name = "Label15";
			this.Label15.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label26 = this.Label15;
			size = new global::System.Drawing.Size(96, 24);
			label26.Size = size;
			this.Label15.TabIndex = 14;
			this.Label15.Text = "Teo Lenght";
			this.Label15.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Label15.Visible = false;
			this.txtTeoLängd.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.txtTeoLängd.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtTeoLängd = this.txtTeoLängd;
			location = new global::System.Drawing.Point(324, 56);
			txtTeoLängd.Location = location;
			this.txtTeoLängd.Name = "txtTeoLängd";
			global::System.Windows.Forms.Control txtTeoLängd2 = this.txtTeoLängd;
			size = new global::System.Drawing.Size(58, 29);
			txtTeoLängd2.Size = size;
			this.txtTeoLängd.TabIndex = 12;
			this.txtTeoLängd.Text = "36.00";
			this.txtTeoLängd.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtTeoLängd.Visible = false;
			global::System.Windows.Forms.Control label27 = this.Label13;
			location = new global::System.Drawing.Point(40, 56);
			label27.Location = location;
			this.Label13.Name = "Label13";
			this.Label13.RightToLeft = global::System.Windows.Forms.RightToLeft.Yes;
			global::System.Windows.Forms.Control label28 = this.Label13;
			size = new global::System.Drawing.Size(96, 24);
			label28.Size = size;
			this.Label13.TabIndex = 10;
			this.Label13.Text = "Bind out kg/s";
			this.Label13.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.lblNoCom.BackColor = global::System.Drawing.Color.FromArgb(255, 192, 128);
			this.lblNoCom.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblNoCom = this.lblNoCom;
			location = new global::System.Drawing.Point(628, 34);
			lblNoCom.Location = location;
			this.lblNoCom.Name = "lblNoCom";
			global::System.Windows.Forms.Control lblNoCom2 = this.lblNoCom;
			size = new global::System.Drawing.Size(208, 24);
			lblNoCom2.Size = size;
			this.lblNoCom.TabIndex = 43;
			this.lblNoCom.Text = "No communication with Fst IPC";
			this.lblNoCom.Visible = false;
			this.tmrInSignaler.Interval = 1000;
			this.GroupBox5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox5;
			location = new global::System.Drawing.Point(826, 90);
			groupBox9.Location = location;
			this.GroupBox5.Name = "GroupBox5";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox5;
			size = new global::System.Drawing.Size(182, 35);
			groupBox10.Size = size;
			this.GroupBox5.TabIndex = 42;
			this.GroupBox5.TabStop = false;
			this.GroupBox5.Text = "Mast Top Position";
			this.tmrPelare.Interval = 1000;
			this.DataGrid1.CaptionText = "Columns today = 23 ";
			this.DataGrid1.CaptionVisible = false;
			this.DataGrid1.DataMember = "";
			this.DataGrid1.HeaderForeColor = global::System.Drawing.SystemColors.ControlText;
			global::System.Windows.Forms.Control dataGrid = this.DataGrid1;
			location = new global::System.Drawing.Point(6, 24);
			dataGrid.Location = location;
			this.DataGrid1.Name = "DataGrid1";
			this.DataGrid1.PreferredColumnWidth = 65;
			this.DataGrid1.RowHeadersVisible = false;
			global::System.Windows.Forms.Control dataGrid2 = this.DataGrid1;
			size = new global::System.Drawing.Size(382, 120);
			dataGrid2.Size = size;
			this.DataGrid1.TabIndex = 0;
			this.DataGrid1.TabStop = false;
			this.GroupBox3.Controls.Add(this.DataGrid1);
			this.GroupBox3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox3;
			location = new global::System.Drawing.Point(618, 250);
			groupBox11.Location = location;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox3;
			size = new global::System.Drawing.Size(390, 152);
			groupBox12.Size = size;
			this.GroupBox3.TabIndex = 40;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Columns Today = None";
			this.KnappF5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF9 = this.KnappF5;
			location = new global::System.Drawing.Point(390, 0);
			knappF9.Location = location;
			this.KnappF5.Name = "KnappF5";
			global::System.Windows.Forms.Control knappF10 = this.KnappF5;
			size = new global::System.Drawing.Size(92, 40);
			knappF10.Size = size;
			this.KnappF5.TabIndex = 4;
			this.KnappF5.TabStop = false;
			this.KnappF5.Text = "F5 = Show Output / m";
			this.lblDjup.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 192);
			this.lblDjup.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lblDjup.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblDjup = this.lblDjup;
			location = new global::System.Drawing.Point(320, 624);
			lblDjup.Location = location;
			this.lblDjup.Name = "lblDjup";
			global::System.Windows.Forms.Control lblDjup2 = this.lblDjup;
			size = new global::System.Drawing.Size(144, 24);
			lblDjup2.Size = size;
			this.lblDjup.TabIndex = 29;
			this.lblDjup.Text = "Depth = 25.00";
			this.lblDjup.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.lblTempKomp.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblTempKomp = this.lblTempKomp;
			location = new global::System.Drawing.Point(120, 256);
			lblTempKomp.Location = location;
			this.lblTempKomp.Name = "lblTempKomp";
			global::System.Windows.Forms.Control lblTempKomp2 = this.lblTempKomp;
			size = new global::System.Drawing.Size(72, 24);
			lblTempKomp2.Size = size;
			this.lblTempKomp.TabIndex = 28;
			this.lblTempKomp.Text = "-15.0  C";
			this.lblTempKomp.TextAlign = global::System.Drawing.ContentAlignment.BottomRight;
			this.lblFuktighet.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblFuktighet = this.lblFuktighet;
			location = new global::System.Drawing.Point(32, 256);
			lblFuktighet.Location = location;
			this.lblFuktighet.Name = "lblFuktighet";
			global::System.Windows.Forms.Control lblFuktighet2 = this.lblFuktighet;
			size = new global::System.Drawing.Size(72, 24);
			lblFuktighet2.Size = size;
			this.lblFuktighet.TabIndex = 27;
			this.lblFuktighet.Text = "25.0 RH";
			this.lblFuktighet.TextAlign = global::System.Drawing.ContentAlignment.BottomRight;
			this.lblTryckRör.Font = new global::System.Drawing.Font("Arial", 12f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblTryckRör = this.lblTryckRör;
			location = new global::System.Drawing.Point(408, 256);
			lblTryckRör.Location = location;
			this.lblTryckRör.Name = "lblTryckRör";
			global::System.Windows.Forms.Control lblTryckRör2 = this.lblTryckRör;
			size = new global::System.Drawing.Size(56, 24);
			lblTryckRör2.Size = size;
			this.lblTryckRör.TabIndex = 26;
			this.lblTryckRör.Text = "Rör";
			this.lblTryckRör.TextAlign = global::System.Drawing.ContentAlignment.BottomRight;
			this.PicUtA8.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA = this.PicUtA8;
			location = new global::System.Drawing.Point(472, 232);
			picUtA.Location = location;
			this.PicUtA8.Name = "PicUtA8";
			global::System.Windows.Forms.Control picUtA2 = this.PicUtA8;
			size = new global::System.Drawing.Size(8, 8);
			picUtA2.Size = size;
			this.PicUtA8.TabIndex = 23;
			this.PicUtA8.TabStop = false;
			this.PicUtA7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA3 = this.PicUtA7;
			location = new global::System.Drawing.Point(480, 232);
			picUtA3.Location = location;
			this.PicUtA7.Name = "PicUtA7";
			global::System.Windows.Forms.Control picUtA4 = this.PicUtA7;
			size = new global::System.Drawing.Size(8, 8);
			picUtA4.Size = size;
			this.PicUtA7.TabIndex = 22;
			this.PicUtA7.TabStop = false;
			this.PicUtA6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA5 = this.PicUtA6;
			location = new global::System.Drawing.Point(480, 240);
			picUtA5.Location = location;
			this.PicUtA6.Name = "PicUtA6";
			global::System.Windows.Forms.Control picUtA6 = this.PicUtA6;
			size = new global::System.Drawing.Size(8, 8);
			picUtA6.Size = size;
			this.PicUtA6.TabIndex = 21;
			this.PicUtA6.TabStop = false;
			this.PicUtA5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA7 = this.PicUtA5;
			location = new global::System.Drawing.Point(480, 248);
			picUtA7.Location = location;
			this.PicUtA5.Name = "PicUtA5";
			global::System.Windows.Forms.Control picUtA8 = this.PicUtA5;
			size = new global::System.Drawing.Size(8, 8);
			picUtA8.Size = size;
			this.PicUtA5.TabIndex = 20;
			this.PicUtA5.TabStop = false;
			this.PicBlåsUt1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt = this.PicBlåsUt1;
			location = new global::System.Drawing.Point(416, 280);
			picBlåsUt.Location = location;
			this.PicBlåsUt1.Name = "PicBlåsUt1";
			global::System.Windows.Forms.Control picBlåsUt2 = this.PicBlåsUt1;
			size = new global::System.Drawing.Size(48, 8);
			picBlåsUt2.Size = size;
			this.PicBlåsUt1.TabIndex = 19;
			this.PicBlåsUt1.TabStop = false;
			this.PicBlåsV.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsV = this.PicBlåsV;
			location = new global::System.Drawing.Point(408, 280);
			picBlåsV.Location = location;
			this.PicBlåsV.Name = "PicBlåsV";
			global::System.Windows.Forms.Control picBlåsV2 = this.PicBlåsV;
			size = new global::System.Drawing.Size(8, 8);
			picBlåsV2.Size = size;
			this.PicBlåsV.TabIndex = 18;
			this.PicBlåsV.TabStop = false;
			this.PicInB1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picInB = this.PicInB1;
			location = new global::System.Drawing.Point(264, 240);
			picInB.Location = location;
			this.PicInB1.Name = "PicInB1";
			global::System.Windows.Forms.Control picInB2 = this.PicInB1;
			size = new global::System.Drawing.Size(8, 40);
			picInB2.Size = size;
			this.PicInB1.TabIndex = 17;
			this.PicInB1.TabStop = false;
			this.KnappF10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF11 = this.KnappF10;
			location = new global::System.Drawing.Point(890, 0);
			knappF11.Location = location;
			this.KnappF10.Name = "KnappF10";
			global::System.Windows.Forms.Control knappF12 = this.KnappF10;
			size = new global::System.Drawing.Size(92, 40);
			knappF12.Size = size;
			this.KnappF10.TabIndex = 9;
			this.KnappF10.TabStop = false;
			this.KnappF10.Text = "F10 = End Application";
			this.KnappF9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF13 = this.KnappF9;
			location = new global::System.Drawing.Point(790, 0);
			knappF13.Location = location;
			this.KnappF9.Name = "KnappF9";
			global::System.Windows.Forms.Control knappF14 = this.KnappF9;
			size = new global::System.Drawing.Size(92, 40);
			knappF14.Size = size;
			this.KnappF9.TabIndex = 8;
			this.KnappF9.TabStop = false;
			this.KnappF9.Text = "F9 = Show Help";
			this.KnappF8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF15 = this.KnappF8;
			location = new global::System.Drawing.Point(690, 0);
			knappF15.Location = location;
			this.KnappF8.Name = "KnappF8";
			global::System.Windows.Forms.Control knappF16 = this.KnappF8;
			size = new global::System.Drawing.Size(92, 40);
			knappF16.Size = size;
			this.KnappF8.TabIndex = 7;
			this.KnappF8.TabStop = false;
			this.KnappF8.Text = "F8 = Disable Tank";
			this.TimerCellmat.Enabled = true;
			this.TimerCellmat.Interval = 200;
			this.lblTeoUt.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lblTeoUt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblTeoUt = this.lblTeoUt;
			location = new global::System.Drawing.Point(320, 562);
			lblTeoUt.Location = location;
			this.lblTeoUt.Name = "lblTeoUt";
			global::System.Windows.Forms.Control lblTeoUt2 = this.lblTeoUt;
			size = new global::System.Drawing.Size(144, 24);
			lblTeoUt2.Size = size;
			this.lblTeoUt.TabIndex = 31;
			this.lblTeoUt.Text = "Teoretical  =   0 kg";
			this.lblTeoUt.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.KnappF7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF17 = this.KnappF7;
			location = new global::System.Drawing.Point(592, 0);
			knappF17.Location = location;
			this.KnappF7.Name = "KnappF7";
			global::System.Windows.Forms.Control knappF18 = this.KnappF7;
			size = new global::System.Drawing.Size(92, 40);
			knappF18.Size = size;
			this.KnappF7.TabIndex = 6;
			this.KnappF7.TabStop = false;
			this.KnappF7.Text = "F7 = Show Inputs";
			this.Panel1.Controls.Add(this.PicBorr);
			this.Panel1.Controls.Add(this.lblTeoUt);
			this.Panel1.Controls.Add(this.lblMättUt);
			this.Panel1.Controls.Add(this.lblDjup);
			this.Panel1.Controls.Add(this.lblTempKomp);
			this.Panel1.Controls.Add(this.lblFuktighet);
			this.Panel1.Controls.Add(this.lblTryckRör);
			this.Panel1.Controls.Add(this.PicUtA8);
			this.Panel1.Controls.Add(this.PicUtA7);
			this.Panel1.Controls.Add(this.PicUtA6);
			this.Panel1.Controls.Add(this.PicUtA5);
			this.Panel1.Controls.Add(this.PicBlåsUt1);
			this.Panel1.Controls.Add(this.PicBlåsV);
			this.Panel1.Controls.Add(this.PicInB1);
			this.Panel1.Controls.Add(this.PicBlåsUt7);
			this.Panel1.Controls.Add(this.PicUtB1);
			this.Panel1.Controls.Add(this.PicBlåsUt6);
			this.Panel1.Controls.Add(this.PicBlåsUt5);
			this.Panel1.Controls.Add(this.PicBlåsUt4);
			this.Panel1.Controls.Add(this.PicBlåsUt3);
			this.Panel1.Controls.Add(this.PicBlåsUt2);
			this.Panel1.Controls.Add(this.PicUtA4);
			this.Panel1.Controls.Add(this.PicUtA3);
			this.Panel1.Controls.Add(this.PicUtA2);
			this.Panel1.Controls.Add(this.PicUtA1);
			this.Panel1.Controls.Add(this.PicCompUt);
			this.Panel1.Controls.Add(this.PicInA1);
			this.Panel1.Controls.Add(this.PicMark);
			this.Panel1.Controls.Add(this.PictureBox2);
			this.Panel1.Controls.Add(this.PictureBox1);
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(12, 34);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(600, 662);
			panel2.Size = size;
			this.Panel1.TabIndex = 36;
			global::System.Windows.Forms.Control picBorr = this.PicBorr;
			location = new global::System.Drawing.Point(492, 48);
			picBorr.Location = location;
			this.PicBorr.Name = "PicBorr";
			global::System.Windows.Forms.Control picBorr2 = this.PicBorr;
			size = new global::System.Drawing.Size(100, 614);
			picBorr2.Size = size;
			this.PicBorr.TabIndex = 3;
			this.PicBorr.TabStop = false;
			this.lblMättUt.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.lblMättUt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control lblMättUt = this.lblMättUt;
			location = new global::System.Drawing.Point(320, 592);
			lblMättUt.Location = location;
			this.lblMättUt.Name = "lblMättUt";
			global::System.Windows.Forms.Control lblMättUt2 = this.lblMättUt;
			size = new global::System.Drawing.Size(144, 24);
			lblMättUt2.Size = size;
			this.lblMättUt.TabIndex = 30;
			this.lblMättUt.Text = "Measured  =   0 kg";
			this.lblMättUt.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.PicBlåsUt7.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt3 = this.PicBlåsUt7;
			location = new global::System.Drawing.Point(538, 24);
			picBlåsUt3.Location = location;
			this.PicBlåsUt7.Name = "PicBlåsUt7";
			global::System.Windows.Forms.Control picBlåsUt4 = this.PicBlåsUt7;
			size = new global::System.Drawing.Size(8, 24);
			picBlåsUt4.Size = size;
			this.PicBlåsUt7.TabIndex = 16;
			this.PicBlåsUt7.TabStop = false;
			this.PicUtB1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtB = this.PicUtB1;
			location = new global::System.Drawing.Point(440, 232);
			picUtB.Location = location;
			this.PicUtB1.Name = "PicUtB1";
			global::System.Windows.Forms.Control picUtB2 = this.PicUtB1;
			size = new global::System.Drawing.Size(24, 8);
			picUtB2.Size = size;
			this.PicUtB1.TabIndex = 15;
			this.PicUtB1.TabStop = false;
			this.PicBlåsUt6.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt5 = this.PicBlåsUt6;
			location = new global::System.Drawing.Point(538, 16);
			picBlåsUt5.Location = location;
			this.PicBlåsUt6.Name = "PicBlåsUt6";
			global::System.Windows.Forms.Control picBlåsUt6 = this.PicBlåsUt6;
			size = new global::System.Drawing.Size(8, 8);
			picBlåsUt6.Size = size;
			this.PicBlåsUt6.TabIndex = 14;
			this.PicBlåsUt6.TabStop = false;
			this.PicBlåsUt5.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt7 = this.PicBlåsUt5;
			location = new global::System.Drawing.Point(472, 16);
			picBlåsUt7.Location = location;
			this.PicBlåsUt5.Name = "PicBlåsUt5";
			global::System.Windows.Forms.Control picBlåsUt8 = this.PicBlåsUt5;
			size = new global::System.Drawing.Size(66, 8);
			picBlåsUt8.Size = size;
			this.PicBlåsUt5.TabIndex = 13;
			this.PicBlåsUt5.TabStop = false;
			this.PicBlåsUt4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt9 = this.PicBlåsUt4;
			location = new global::System.Drawing.Point(464, 16);
			picBlåsUt9.Location = location;
			this.PicBlåsUt4.Name = "PicBlåsUt4";
			global::System.Windows.Forms.Control picBlåsUt10 = this.PicBlåsUt4;
			size = new global::System.Drawing.Size(8, 8);
			picBlåsUt10.Size = size;
			this.PicBlåsUt4.TabIndex = 12;
			this.PicBlåsUt4.TabStop = false;
			this.PicBlåsUt3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt11 = this.PicBlåsUt3;
			location = new global::System.Drawing.Point(464, 24);
			picBlåsUt11.Location = location;
			this.PicBlåsUt3.Name = "PicBlåsUt3";
			global::System.Windows.Forms.Control picBlåsUt12 = this.PicBlåsUt3;
			size = new global::System.Drawing.Size(8, 256);
			picBlåsUt12.Size = size;
			this.PicBlåsUt3.TabIndex = 11;
			this.PicBlåsUt3.TabStop = false;
			this.PicBlåsUt2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picBlåsUt13 = this.PicBlåsUt2;
			location = new global::System.Drawing.Point(464, 280);
			picBlåsUt13.Location = location;
			this.PicBlåsUt2.Name = "PicBlåsUt2";
			global::System.Windows.Forms.Control picBlåsUt14 = this.PicBlåsUt2;
			size = new global::System.Drawing.Size(8, 8);
			picBlåsUt14.Size = size;
			this.PicBlåsUt2.TabIndex = 10;
			this.PicBlåsUt2.TabStop = false;
			this.PicUtA4.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA9 = this.PicUtA4;
			location = new global::System.Drawing.Point(208, 248);
			picUtA9.Location = location;
			this.PicUtA4.Name = "PicUtA4";
			global::System.Windows.Forms.Control picUtA10 = this.PicUtA4;
			size = new global::System.Drawing.Size(272, 8);
			picUtA10.Size = size;
			this.PicUtA4.TabIndex = 9;
			this.PicUtA4.TabStop = false;
			this.PicUtA3.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA11 = this.PicUtA3;
			location = new global::System.Drawing.Point(200, 248);
			picUtA11.Location = location;
			this.PicUtA3.Name = "PicUtA3";
			global::System.Windows.Forms.Control picUtA12 = this.PicUtA3;
			size = new global::System.Drawing.Size(8, 8);
			picUtA12.Size = size;
			this.PicUtA3.TabIndex = 8;
			this.PicUtA3.TabStop = false;
			this.PicUtA2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA13 = this.PicUtA2;
			location = new global::System.Drawing.Point(200, 240);
			picUtA13.Location = location;
			this.PicUtA2.Name = "PicUtA2";
			global::System.Windows.Forms.Control picUtA14 = this.PicUtA2;
			size = new global::System.Drawing.Size(8, 8);
			picUtA14.Size = size;
			this.PicUtA2.TabIndex = 7;
			this.PicUtA2.TabStop = false;
			this.PicUtA1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picUtA15 = this.PicUtA1;
			location = new global::System.Drawing.Point(200, 232);
			picUtA15.Location = location;
			this.PicUtA1.Name = "PicUtA1";
			global::System.Windows.Forms.Control picUtA16 = this.PicUtA1;
			size = new global::System.Drawing.Size(8, 8);
			picUtA16.Size = size;
			this.PicUtA1.TabIndex = 6;
			this.PicUtA1.TabStop = false;
			this.PicCompUt.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picCompUt = this.PicCompUt;
			location = new global::System.Drawing.Point(0, 280);
			picCompUt.Location = location;
			this.PicCompUt.Name = "PicCompUt";
			global::System.Windows.Forms.Control picCompUt2 = this.PicCompUt;
			size = new global::System.Drawing.Size(416, 8);
			picCompUt2.Size = size;
			this.PicCompUt.TabIndex = 5;
			this.PicCompUt.TabStop = false;
			this.PicInA1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picInA = this.PicInA1;
			location = new global::System.Drawing.Point(24, 240);
			picInA.Location = location;
			this.PicInA1.Name = "PicInA1";
			global::System.Windows.Forms.Control picInA2 = this.PicInA1;
			size = new global::System.Drawing.Size(8, 40);
			picInA2.Size = size;
			this.PicInA1.TabIndex = 4;
			this.PicInA1.TabStop = false;
			this.PicMark.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control picMark = this.PicMark;
			location = new global::System.Drawing.Point(0, 298);
			picMark.Location = location;
			this.PicMark.Name = "PicMark";
			global::System.Windows.Forms.Control picMark2 = this.PicMark;
			size = new global::System.Drawing.Size(492, 364);
			picMark2.Size = size;
			this.PicMark.TabIndex = 2;
			this.PicMark.TabStop = false;
			this.PictureBox2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control pictureBox = this.PictureBox2;
			location = new global::System.Drawing.Point(240, 0);
			pictureBox.Location = location;
			this.PictureBox2.Name = "PictureBox2";
			global::System.Windows.Forms.Control pictureBox2 = this.PictureBox2;
			size = new global::System.Drawing.Size(200, 240);
			pictureBox2.Size = size;
			this.PictureBox2.TabIndex = 1;
			this.PictureBox2.TabStop = false;
			this.PictureBox1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			global::System.Windows.Forms.Control pictureBox3 = this.PictureBox1;
			location = new global::System.Drawing.Point(0, 0);
			pictureBox3.Location = location;
			this.PictureBox1.Name = "PictureBox1";
			global::System.Windows.Forms.Control pictureBox4 = this.PictureBox1;
			size = new global::System.Drawing.Size(200, 240);
			pictureBox4.Size = size;
			this.PictureBox1.TabIndex = 0;
			this.PictureBox1.TabStop = false;
			this.Label2.Font = new global::System.Drawing.Font("Arial", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Label2.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control label29 = this.Label2;
			location = new global::System.Drawing.Point(852, 50);
			label29.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label30 = this.Label2;
			size = new global::System.Drawing.Size(168, 32);
			label30.Size = size;
			this.Label2.TabIndex = 35;
			this.Label2.Text = "Serial no: 1472";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.lblJunttan.Font = new global::System.Drawing.Font("Arial", 18f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblJunttan.ForeColor = global::System.Drawing.Color.Blue;
			global::System.Windows.Forms.Control lblJunttan = this.lblJunttan;
			location = new global::System.Drawing.Point(844, 18);
			lblJunttan.Location = location;
			this.lblJunttan.Name = "lblJunttan";
			global::System.Windows.Forms.Control lblJunttan2 = this.lblJunttan;
			size = new global::System.Drawing.Size(176, 32);
			lblJunttan2.Size = size;
			this.lblJunttan.TabIndex = 34;
			this.lblJunttan.Text = "Junttan DS 18";
			this.lblJunttan.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.Panel2.Controls.Add(this.KnappF10);
			this.Panel2.Controls.Add(this.KnappF9);
			this.Panel2.Controls.Add(this.KnappF8);
			this.Panel2.Controls.Add(this.KnappF7);
			this.Panel2.Controls.Add(this.KnappF6);
			this.Panel2.Controls.Add(this.KnappF5);
			this.Panel2.Controls.Add(this.KnappF4);
			this.Panel2.Controls.Add(this.KnappF3);
			this.Panel2.Controls.Add(this.KnappF2);
			this.Panel2.Controls.Add(this.KnappF1);
			global::System.Windows.Forms.Control panel3 = this.Panel2;
			location = new global::System.Drawing.Point(22, 701);
			panel3.Location = location;
			this.Panel2.Name = "Panel2";
			global::System.Windows.Forms.Control panel4 = this.Panel2;
			size = new global::System.Drawing.Size(1016, 40);
			panel4.Size = size;
			this.Panel2.TabIndex = 37;
			this.KnappF6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control knappF19 = this.KnappF6;
			location = new global::System.Drawing.Point(490, 0);
			knappF19.Location = location;
			this.KnappF6.Name = "KnappF6";
			global::System.Windows.Forms.Control knappF20 = this.KnappF6;
			size = new global::System.Drawing.Size(92, 40);
			knappF20.Size = size;
			this.KnappF6.TabIndex = 5;
			this.KnappF6.TabStop = false;
			this.KnappF6.Text = "F6 = Show Settings";
			this.lblInfoFst.AutoSize = true;
			this.lblInfoFst.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lblInfoFst.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control lblInfoFst = this.lblInfoFst;
			location = new global::System.Drawing.Point(628, 66);
			lblInfoFst.Location = location;
			this.lblInfoFst.Name = "lblInfoFst";
			global::System.Windows.Forms.Control lblInfoFst2 = this.lblInfoFst;
			size = new global::System.Drawing.Size(0, 16);
			lblInfoFst2.Size = size;
			this.lblInfoFst.TabIndex = 45;
			this.txtDjupHåkan.BackColor = global::System.Drawing.Color.FromArgb(255, 255, 128);
			this.txtDjupHåkan.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtDjupHåkan = this.txtDjupHåkan;
			location = new global::System.Drawing.Point(524, 2);
			txtDjupHåkan.Location = location;
			this.txtDjupHåkan.Name = "txtDjupHåkan";
			global::System.Windows.Forms.Control txtDjupHåkan2 = this.txtDjupHåkan;
			size = new global::System.Drawing.Size(56, 29);
			txtDjupHåkan2.Size = size;
			this.txtDjupHåkan.TabIndex = 46;
			this.txtDjupHåkan.Text = "0";
			this.txtDjupHåkan.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.SerieNovatron.PortName = "COM7";
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(1009, 746);
			this.ClientSize = size;
			this.Controls.Add(this.txtDjupHåkan);
			this.Controls.Add(this.lblInfoFst);
			this.Controls.Add(this.GroupBox2);
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.GroupBox4);
			this.Controls.Add(this.GroupBox6);
			this.Controls.Add(this.lblNoCom);
			this.Controls.Add(this.GroupBox5);
			this.Controls.Add(this.GroupBox3);
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.lblJunttan);
			this.Controls.Add(this.Panel2);
			this.DoubleBuffered = true;
			this.KeyPreview = true;
			this.Name = "frmTestDrill";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Form2";
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGrid1).EndInit();
			this.GroupBox3.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsV).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicInB1).EndInit();
			this.Panel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.PicBorr).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtB1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicBlåsUt2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicUtA1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicCompUt).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicInA1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PicMark).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.Panel2.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040001B4 RID: 436
		private global::System.ComponentModel.IContainer components;
	}
}
