namespace winKCdrill2
{
	// Token: 0x0200000D RID: 13
	//[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class TestarKom : global::System.Windows.Forms.Form
	{
		// Token: 0x06000152 RID: 338 RVA: 0x00036E24 File Offset: 0x00035224
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06000153 RID: 339 RVA: 0x00036E44 File Offset: 0x00035244
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			this.KntrlComPort = new global::System.Windows.Forms.Timer(this.components);
			this.GroupBoxStatus = new global::System.Windows.Forms.GroupBox();
			this.TextMottagsFel = new global::System.Windows.Forms.TextBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextByteSek = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.TextUppdatesSek = new global::System.Windows.Forms.TextBox();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.TextComRestarts = new global::System.Windows.Forms.TextBox();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.TextIPCver = new global::System.Windows.Forms.TextBox();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.GroupMätVärden = new global::System.Windows.Forms.GroupBox();
			this.NUpGround = new global::System.Windows.Forms.NumericUpDown();
			this.ComboBoxports = new global::System.Windows.Forms.ComboBox();
			this.TextTankBgh = new global::System.Windows.Forms.TextBox();
			this.TextTankAhg = new global::System.Windows.Forms.TextBox();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label26 = new global::System.Windows.Forms.Label();
			this.Label27 = new global::System.Windows.Forms.Label();
			this.Label28 = new global::System.Windows.Forms.Label();
			this.TextTankAViktH = new global::System.Windows.Forms.TextBox();
			this.Label41 = new global::System.Windows.Forms.Label();
			this.TextTankBViktH = new global::System.Windows.Forms.TextBox();
			this.Label23 = new global::System.Windows.Forms.Label();
			this.Label29 = new global::System.Windows.Forms.Label();
			this.TextStatusVärden = new global::System.Windows.Forms.TextBox();
			this.Label30 = new global::System.Windows.Forms.Label();
			this.TextUtCellB = new global::System.Windows.Forms.TextBox();
			this.Label31 = new global::System.Windows.Forms.Label();
			this.TextUtCellA = new global::System.Windows.Forms.TextBox();
			this.Label32 = new global::System.Windows.Forms.Label();
			this.TextUtRotation = new global::System.Windows.Forms.TextBox();
			this.Label33 = new global::System.Windows.Forms.Label();
			this.TextUtUppNer = new global::System.Windows.Forms.TextBox();
			this.Label34 = new global::System.Windows.Forms.Label();
			this.TextINPotB = new global::System.Windows.Forms.TextBox();
			this.Label35 = new global::System.Windows.Forms.Label();
			this.TextInPotA = new global::System.Windows.Forms.TextBox();
			this.Label36 = new global::System.Windows.Forms.Label();
			this.TextLuftFukt = new global::System.Windows.Forms.TextBox();
			this.Label37 = new global::System.Windows.Forms.Label();
			this.TextStatusAirValves = new global::System.Windows.Forms.TextBox();
			this.Label38 = new global::System.Windows.Forms.Label();
			this.TextCarrier = new global::System.Windows.Forms.TextBox();
			this.Label39 = new global::System.Windows.Forms.Label();
			this.TextInstaller = new global::System.Windows.Forms.TextBox();
			this.Label40 = new global::System.Windows.Forms.Label();
			this.Label22 = new global::System.Windows.Forms.Label();
			this.TextKomprTemp = new global::System.Windows.Forms.TextBox();
			this.TextTankBTemp = new global::System.Windows.Forms.TextBox();
			this.Label24 = new global::System.Windows.Forms.Label();
			this.TextTankATemp = new global::System.Windows.Forms.TextBox();
			this.Label25 = new global::System.Windows.Forms.Label();
			this.TextBorrDjup = new global::System.Windows.Forms.TextBox();
			this.Label18 = new global::System.Windows.Forms.Label();
			this.TextCellBSpeed = new global::System.Windows.Forms.TextBox();
			this.Label19 = new global::System.Windows.Forms.Label();
			this.TextCellASpeed = new global::System.Windows.Forms.TextBox();
			this.Label20 = new global::System.Windows.Forms.Label();
			this.TextBorrSpeed = new global::System.Windows.Forms.TextBox();
			this.Label21 = new global::System.Windows.Forms.Label();
			this.TextTankBerror = new global::System.Windows.Forms.TextBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.TextTankBViktL = new global::System.Windows.Forms.TextBox();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.TextTankAError = new global::System.Windows.Forms.TextBox();
			this.Label16 = new global::System.Windows.Forms.Label();
			this.TextTankAViktL = new global::System.Windows.Forms.TextBox();
			this.Label17 = new global::System.Windows.Forms.Label();
			this.TextTankBTryck = new global::System.Windows.Forms.TextBox();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.TextTankATryck = new global::System.Windows.Forms.TextBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.TextSlangTryck = new global::System.Windows.Forms.TextBox();
			this.Label12 = new global::System.Windows.Forms.Label();
			this.TextSvivelTryck = new global::System.Windows.Forms.TextBox();
			this.Label13 = new global::System.Windows.Forms.Label();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button2 = new global::System.Windows.Forms.Button();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.RadioDriver4 = new global::System.Windows.Forms.RadioButton();
			this.TextDriver4 = new global::System.Windows.Forms.TextBox();
			this.RadioDriver3 = new global::System.Windows.Forms.RadioButton();
			this.TextDriver3 = new global::System.Windows.Forms.TextBox();
			this.RadioDriver2 = new global::System.Windows.Forms.RadioButton();
			this.TextDriver2 = new global::System.Windows.Forms.TextBox();
			this.RadioDriver1 = new global::System.Windows.Forms.RadioButton();
			this.TextDriver1 = new global::System.Windows.Forms.TextBox();
			this.chkNovatron = new global::System.Windows.Forms.CheckBox();
			this.GroupBoxStatus.SuspendLayout();
			this.GroupMätVärden.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.NUpGround).BeginInit();
			this.GroupBox1.SuspendLayout();
			this.SuspendLayout();
			this.KntrlComPort.Interval = 1000;
			this.GroupBoxStatus.Controls.Add(this.TextMottagsFel);
			this.GroupBoxStatus.Controls.Add(this.Label1);
			this.GroupBoxStatus.Controls.Add(this.TextByteSek);
			this.GroupBoxStatus.Controls.Add(this.Label9);
			this.GroupBoxStatus.Controls.Add(this.TextUppdatesSek);
			this.GroupBoxStatus.Controls.Add(this.Label8);
			this.GroupBoxStatus.Controls.Add(this.TextComRestarts);
			this.GroupBoxStatus.Controls.Add(this.Label7);
			this.GroupBoxStatus.Controls.Add(this.TextIPCver);
			this.GroupBoxStatus.Controls.Add(this.Label6);
			this.GroupBoxStatus.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBoxStatus = this.GroupBoxStatus;
			global::System.Drawing.Point location = new global::System.Drawing.Point(31, 12);
			groupBoxStatus.Location = location;
			this.GroupBoxStatus.Name = "GroupBoxStatus";
			global::System.Windows.Forms.Control groupBoxStatus2 = this.GroupBoxStatus;
			global::System.Drawing.Size size = new global::System.Drawing.Size(326, 188);
			groupBoxStatus2.Size = size;
			this.GroupBoxStatus.TabIndex = 5;
			this.GroupBoxStatus.TabStop = false;
			this.GroupBoxStatus.Text = "Status of Comunication";
			this.TextMottagsFel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textMottagsFel = this.TextMottagsFel;
			location = new global::System.Drawing.Point(176, 143);
			textMottagsFel.Location = location;
			this.TextMottagsFel.Name = "TextMottagsFel";
			this.TextMottagsFel.ReadOnly = true;
			global::System.Windows.Forms.Control textMottagsFel2 = this.TextMottagsFel;
			size = new global::System.Drawing.Size(136, 22);
			textMottagsFel2.Size = size;
			this.TextMottagsFel.TabIndex = 9;
			this.TextMottagsFel.Text = "No communication";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(22, 146);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(97, 16);
			label2.Size = size;
			this.Label1.TabIndex = 8;
			this.Label1.Text = "Recieve errors";
			this.TextByteSek.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textByteSek = this.TextByteSek;
			location = new global::System.Drawing.Point(176, 113);
			textByteSek.Location = location;
			this.TextByteSek.Name = "TextByteSek";
			this.TextByteSek.ReadOnly = true;
			global::System.Windows.Forms.Control textByteSek2 = this.TextByteSek;
			size = new global::System.Drawing.Size(136, 22);
			textByteSek2.Size = size;
			this.TextByteSek.TabIndex = 7;
			this.TextByteSek.Text = "No communication";
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label3 = this.Label9;
			location = new global::System.Drawing.Point(22, 116);
			label3.Location = location;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label4 = this.Label9;
			size = new global::System.Drawing.Size(74, 16);
			label4.Size = size;
			this.Label9.TabIndex = 6;
			this.Label9.Text = "Bytes / sec";
			this.TextUppdatesSek.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textUppdatesSek = this.TextUppdatesSek;
			location = new global::System.Drawing.Point(176, 85);
			textUppdatesSek.Location = location;
			this.TextUppdatesSek.Name = "TextUppdatesSek";
			this.TextUppdatesSek.ReadOnly = true;
			global::System.Windows.Forms.Control textUppdatesSek2 = this.TextUppdatesSek;
			size = new global::System.Drawing.Size(136, 22);
			textUppdatesSek2.Size = size;
			this.TextUppdatesSek.TabIndex = 5;
			this.TextUppdatesSek.Text = "No communication";
			this.Label8.AutoSize = true;
			this.Label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label5 = this.Label8;
			location = new global::System.Drawing.Point(22, 88);
			label5.Location = location;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label6 = this.Label8;
			size = new global::System.Drawing.Size(92, 16);
			label6.Size = size;
			this.Label8.TabIndex = 4;
			this.Label8.Text = "Updates / sec";
			this.TextComRestarts.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textComRestarts = this.TextComRestarts;
			location = new global::System.Drawing.Point(176, 57);
			textComRestarts.Location = location;
			this.TextComRestarts.Name = "TextComRestarts";
			this.TextComRestarts.ReadOnly = true;
			global::System.Windows.Forms.Control textComRestarts2 = this.TextComRestarts;
			size = new global::System.Drawing.Size(136, 22);
			textComRestarts2.Size = size;
			this.TextComRestarts.TabIndex = 3;
			this.Label7.AutoSize = true;
			this.Label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label7 = this.Label7;
			location = new global::System.Drawing.Point(22, 60);
			label7.Location = location;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label8 = this.Label7;
			size = new global::System.Drawing.Size(103, 16);
			label8.Size = size;
			this.Label7.TabIndex = 2;
			this.Label7.Text = "Restarts of Com";
			this.TextIPCver.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textIPCver = this.TextIPCver;
			location = new global::System.Drawing.Point(176, 29);
			textIPCver.Location = location;
			this.TextIPCver.Name = "TextIPCver";
			this.TextIPCver.ReadOnly = true;
			global::System.Windows.Forms.Control textIPCver2 = this.TextIPCver;
			size = new global::System.Drawing.Size(136, 22);
			textIPCver2.Size = size;
			this.TextIPCver.TabIndex = 1;
			this.TextIPCver.Text = "No communication";
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label9 = this.Label6;
			location = new global::System.Drawing.Point(22, 32);
			label9.Location = location;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label10 = this.Label6;
			size = new global::System.Drawing.Size(136, 16);
			label10.Size = size;
			this.Label6.TabIndex = 0;
			this.Label6.Text = "Version IPC controller";
			this.Label2.AutoSize = true;
			global::System.Windows.Forms.Control label11 = this.Label2;
			location = new global::System.Drawing.Point(395, 12);
			label11.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label12 = this.Label2;
			size = new global::System.Drawing.Size(39, 13);
			label12.Size = size;
			this.Label2.TabIndex = 6;
			this.Label2.Text = "Label2";
			this.Label3.AutoSize = true;
			global::System.Windows.Forms.Control label13 = this.Label3;
			location = new global::System.Drawing.Point(495, 12);
			label13.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label14 = this.Label3;
			size = new global::System.Drawing.Size(39, 13);
			label14.Size = size;
			this.Label3.TabIndex = 7;
			this.Label3.Text = "Label3";
			this.Label4.AutoSize = true;
			global::System.Windows.Forms.Control label15 = this.Label4;
			location = new global::System.Drawing.Point(591, 12);
			label15.Location = location;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label16 = this.Label4;
			size = new global::System.Drawing.Size(39, 13);
			label16.Size = size;
			this.Label4.TabIndex = 8;
			this.Label4.Text = "Label4";
			this.Label5.AutoSize = true;
			global::System.Windows.Forms.Control label17 = this.Label5;
			location = new global::System.Drawing.Point(667, 12);
			label17.Location = location;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label18 = this.Label5;
			size = new global::System.Drawing.Size(39, 13);
			label18.Size = size;
			this.Label5.TabIndex = 9;
			this.Label5.Text = "Label5";
			this.GroupMätVärden.Controls.Add(this.chkNovatron);
			this.GroupMätVärden.Controls.Add(this.NUpGround);
			this.GroupMätVärden.Controls.Add(this.ComboBoxports);
			this.GroupMätVärden.Controls.Add(this.TextTankBgh);
			this.GroupMätVärden.Controls.Add(this.TextTankAhg);
			this.GroupMätVärden.Controls.Add(this.TextBox1);
			this.GroupMätVärden.Controls.Add(this.Label26);
			this.GroupMätVärden.Controls.Add(this.Label27);
			this.GroupMätVärden.Controls.Add(this.Label28);
			this.GroupMätVärden.Controls.Add(this.TextTankAViktH);
			this.GroupMätVärden.Controls.Add(this.Label41);
			this.GroupMätVärden.Controls.Add(this.TextTankBViktH);
			this.GroupMätVärden.Controls.Add(this.Label23);
			this.GroupMätVärden.Controls.Add(this.Label29);
			this.GroupMätVärden.Controls.Add(this.TextStatusVärden);
			this.GroupMätVärden.Controls.Add(this.Label30);
			this.GroupMätVärden.Controls.Add(this.TextUtCellB);
			this.GroupMätVärden.Controls.Add(this.Label31);
			this.GroupMätVärden.Controls.Add(this.TextUtCellA);
			this.GroupMätVärden.Controls.Add(this.Label32);
			this.GroupMätVärden.Controls.Add(this.TextUtRotation);
			this.GroupMätVärden.Controls.Add(this.Label33);
			this.GroupMätVärden.Controls.Add(this.TextUtUppNer);
			this.GroupMätVärden.Controls.Add(this.Label34);
			this.GroupMätVärden.Controls.Add(this.TextINPotB);
			this.GroupMätVärden.Controls.Add(this.Label35);
			this.GroupMätVärden.Controls.Add(this.TextInPotA);
			this.GroupMätVärden.Controls.Add(this.Label36);
			this.GroupMätVärden.Controls.Add(this.TextLuftFukt);
			this.GroupMätVärden.Controls.Add(this.Label37);
			this.GroupMätVärden.Controls.Add(this.TextStatusAirValves);
			this.GroupMätVärden.Controls.Add(this.Label38);
			this.GroupMätVärden.Controls.Add(this.TextCarrier);
			this.GroupMätVärden.Controls.Add(this.Label39);
			this.GroupMätVärden.Controls.Add(this.TextInstaller);
			this.GroupMätVärden.Controls.Add(this.Label40);
			this.GroupMätVärden.Controls.Add(this.Label22);
			this.GroupMätVärden.Controls.Add(this.TextKomprTemp);
			this.GroupMätVärden.Controls.Add(this.TextTankBTemp);
			this.GroupMätVärden.Controls.Add(this.Label24);
			this.GroupMätVärden.Controls.Add(this.TextTankATemp);
			this.GroupMätVärden.Controls.Add(this.Label25);
			this.GroupMätVärden.Controls.Add(this.TextBorrDjup);
			this.GroupMätVärden.Controls.Add(this.Label18);
			this.GroupMätVärden.Controls.Add(this.TextCellBSpeed);
			this.GroupMätVärden.Controls.Add(this.Label19);
			this.GroupMätVärden.Controls.Add(this.TextCellASpeed);
			this.GroupMätVärden.Controls.Add(this.Label20);
			this.GroupMätVärden.Controls.Add(this.TextBorrSpeed);
			this.GroupMätVärden.Controls.Add(this.Label21);
			this.GroupMätVärden.Controls.Add(this.TextTankBerror);
			this.GroupMätVärden.Controls.Add(this.Label14);
			this.GroupMätVärden.Controls.Add(this.TextTankBViktL);
			this.GroupMätVärden.Controls.Add(this.Label15);
			this.GroupMätVärden.Controls.Add(this.TextTankAError);
			this.GroupMätVärden.Controls.Add(this.Label16);
			this.GroupMätVärden.Controls.Add(this.TextTankAViktL);
			this.GroupMätVärden.Controls.Add(this.Label17);
			this.GroupMätVärden.Controls.Add(this.TextTankBTryck);
			this.GroupMätVärden.Controls.Add(this.Label10);
			this.GroupMätVärden.Controls.Add(this.TextTankATryck);
			this.GroupMätVärden.Controls.Add(this.Label11);
			this.GroupMätVärden.Controls.Add(this.TextSlangTryck);
			this.GroupMätVärden.Controls.Add(this.Label12);
			this.GroupMätVärden.Controls.Add(this.TextSvivelTryck);
			this.GroupMätVärden.Controls.Add(this.Label13);
			this.GroupMätVärden.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupMätVärden = this.GroupMätVärden;
			location = new global::System.Drawing.Point(31, 206);
			groupMätVärden.Location = location;
			this.GroupMätVärden.Name = "GroupMätVärden";
			global::System.Windows.Forms.Control groupMätVärden2 = this.GroupMätVärden;
			size = new global::System.Drawing.Size(794, 519);
			groupMätVärden2.Size = size;
			this.GroupMätVärden.TabIndex = 10;
			this.GroupMätVärden.TabStop = false;
			this.GroupMätVärden.Text = "Maesured Values";
			this.NUpGround.DecimalPlaces = 2;
			global::System.Windows.Forms.NumericUpDown nupGround = this.NUpGround;
			decimal num = new decimal(new int[]
			{
				1,
				0,
				0,
				65536
			});
			nupGround.Increment = num;
			global::System.Windows.Forms.Control nupGround2 = this.NUpGround;
			location = new global::System.Drawing.Point(563, 429);
			nupGround2.Location = location;
			global::System.Windows.Forms.NumericUpDown nupGround3 = this.NUpGround;
			num = new decimal(new int[]
			{
				2000,
				0,
				0,
				0
			});
			nupGround3.Maximum = num;
			global::System.Windows.Forms.NumericUpDown nupGround4 = this.NUpGround;
			num = new decimal(new int[]
			{
				100,
				0,
				0,
				int.MinValue
			});
			nupGround4.Minimum = num;
			this.NUpGround.Name = "NUpGround";
			global::System.Windows.Forms.Control nupGround5 = this.NUpGround;
			size = new global::System.Drawing.Size(136, 22);
			nupGround5.Size = size;
			this.NUpGround.TabIndex = 75;
			this.NUpGround.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.ComboBoxports.Enabled = false;
			this.ComboBoxports.FormattingEnabled = true;
			global::System.Windows.Forms.Control comboBoxports = this.ComboBoxports;
			location = new global::System.Drawing.Point(563, 399);
			comboBoxports.Location = location;
			this.ComboBoxports.Name = "ComboBoxports";
			global::System.Windows.Forms.Control comboBoxports2 = this.ComboBoxports;
			size = new global::System.Drawing.Size(136, 24);
			comboBoxports2.Size = size;
			this.ComboBoxports.TabIndex = 74;
			this.TextTankBgh.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBgh = this.TextTankBgh;
			location = new global::System.Drawing.Point(318, 205);
			textTankBgh.Location = location;
			this.TextTankBgh.Name = "TextTankBgh";
			this.TextTankBgh.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBgh2 = this.TextTankBgh;
			size = new global::System.Drawing.Size(85, 22);
			textTankBgh2.Size = size;
			this.TextTankBgh.TabIndex = 73;
			this.TextTankAhg.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankAhg = this.TextTankAhg;
			location = new global::System.Drawing.Point(318, 149);
			textTankAhg.Location = location;
			this.TextTankAhg.Name = "TextTankAhg";
			this.TextTankAhg.ReadOnly = true;
			global::System.Windows.Forms.Control textTankAhg2 = this.TextTankAhg;
			size = new global::System.Drawing.Size(85, 22);
			textTankAhg2.Size = size;
			this.TextTankAhg.TabIndex = 72;
			this.TextBox1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(563, 487);
			textBox.Location = location;
			this.TextBox1.Name = "TextBox1";
			this.TextBox1.ReadOnly = true;
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(136, 22);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 71;
			this.TextBox1.Text = "Nop";
			this.Label26.AutoSize = true;
			this.Label26.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label19 = this.Label26;
			location = new global::System.Drawing.Point(409, 364);
			label19.Location = location;
			this.Label26.Name = "Label26";
			global::System.Windows.Forms.Control label20 = this.Label26;
			size = new global::System.Drawing.Size(90, 16);
			label20.Size = size;
			this.Label26.TabIndex = 70;
			this.Label26.Text = "Status Values";
			this.Label27.AutoSize = true;
			this.Label27.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label21 = this.Label27;
			location = new global::System.Drawing.Point(409, 490);
			label21.Location = location;
			this.Label27.Name = "Label27";
			global::System.Windows.Forms.Control label22 = this.Label27;
			size = new global::System.Drawing.Size(45, 16);
			label22.Size = size;
			this.Label27.TabIndex = 68;
			this.Label27.Text = "Spare";
			this.Label28.AutoSize = true;
			this.Label28.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label23 = this.Label28;
			location = new global::System.Drawing.Point(409, 462);
			label23.Location = location;
			this.Label28.Name = "Label28";
			global::System.Windows.Forms.Control label24 = this.Label28;
			size = new global::System.Drawing.Size(94, 16);
			label24.Size = size;
			this.Label28.TabIndex = 66;
			this.Label28.Text = "Novatron Com";
			this.TextTankAViktH.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankAViktH = this.TextTankAViktH;
			location = new global::System.Drawing.Point(176, 177);
			textTankAViktH.Location = location;
			this.TextTankAViktH.Name = "TextTankAViktH";
			this.TextTankAViktH.ReadOnly = true;
			global::System.Windows.Forms.Control textTankAViktH2 = this.TextTankAViktH;
			size = new global::System.Drawing.Size(136, 22);
			textTankAViktH2.Size = size;
			this.TextTankAViktH.TabIndex = 41;
			this.Label41.AutoSize = true;
			this.Label41.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label25 = this.Label41;
			location = new global::System.Drawing.Point(22, 179);
			label25.Location = location;
			this.Label41.Name = "Label41";
			global::System.Windows.Forms.Control label26 = this.Label41;
			size = new global::System.Drawing.Size(132, 16);
			label26.Size = size;
			this.Label41.TabIndex = 40;
			this.Label41.Text = "Tank A Weight (high)";
			this.TextTankBViktH.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBViktH = this.TextTankBViktH;
			location = new global::System.Drawing.Point(176, 233);
			textTankBViktH.Location = location;
			this.TextTankBViktH.Name = "TextTankBViktH";
			this.TextTankBViktH.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBViktH2 = this.TextTankBViktH;
			size = new global::System.Drawing.Size(136, 22);
			textTankBViktH2.Size = size;
			this.TextTankBViktH.TabIndex = 39;
			this.Label23.AutoSize = true;
			this.Label23.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label27 = this.Label23;
			location = new global::System.Drawing.Point(22, 236);
			label27.Location = location;
			this.Label23.Name = "Label23";
			global::System.Windows.Forms.Control label28 = this.Label23;
			size = new global::System.Drawing.Size(132, 16);
			label28.Size = size;
			this.Label23.TabIndex = 36;
			this.Label23.Text = "Tank B Weight (high)";
			this.Label29.AutoSize = true;
			this.Label29.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label29 = this.Label29;
			location = new global::System.Drawing.Point(409, 434);
			label29.Location = location;
			this.Label29.Name = "Label29";
			global::System.Windows.Forms.Control label30 = this.Label29;
			size = new global::System.Drawing.Size(108, 16);
			label30.Size = size;
			this.Label29.TabIndex = 64;
			this.Label29.Text = "Heigth of Ground";
			this.TextStatusVärden.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textStatusVärden = this.TextStatusVärden;
			location = new global::System.Drawing.Point(563, 361);
			textStatusVärden.Location = location;
			this.TextStatusVärden.Name = "TextStatusVärden";
			this.TextStatusVärden.ReadOnly = true;
			global::System.Windows.Forms.Control textStatusVärden2 = this.TextStatusVärden;
			size = new global::System.Drawing.Size(136, 22);
			textStatusVärden2.Size = size;
			this.TextStatusVärden.TabIndex = 63;
			this.Label30.AutoSize = true;
			this.Label30.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label31 = this.Label30;
			location = new global::System.Drawing.Point(409, 406);
			label31.Location = location;
			this.Label30.Name = "Label30";
			global::System.Windows.Forms.Control label32 = this.Label30;
			size = new global::System.Drawing.Size(92, 16);
			label32.Size = size;
			this.Label30.TabIndex = 62;
			this.Label30.Text = "Comport used";
			this.TextUtCellB.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textUtCellB = this.TextUtCellB;
			location = new global::System.Drawing.Point(563, 333);
			textUtCellB.Location = location;
			this.TextUtCellB.Name = "TextUtCellB";
			this.TextUtCellB.ReadOnly = true;
			global::System.Windows.Forms.Control textUtCellB2 = this.TextUtCellB;
			size = new global::System.Drawing.Size(136, 22);
			textUtCellB2.Size = size;
			this.TextUtCellB.TabIndex = 61;
			this.Label31.AutoSize = true;
			this.Label31.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label33 = this.Label31;
			location = new global::System.Drawing.Point(409, 336);
			label33.Location = location;
			this.Label31.Name = "Label31";
			global::System.Windows.Forms.Control label34 = this.Label31;
			size = new global::System.Drawing.Size(87, 16);
			label34.Size = size;
			this.Label31.TabIndex = 60;
			this.Label31.Text = "Out Feeder B";
			this.TextUtCellA.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textUtCellA = this.TextUtCellA;
			location = new global::System.Drawing.Point(563, 305);
			textUtCellA.Location = location;
			this.TextUtCellA.Name = "TextUtCellA";
			this.TextUtCellA.ReadOnly = true;
			global::System.Windows.Forms.Control textUtCellA2 = this.TextUtCellA;
			size = new global::System.Drawing.Size(136, 22);
			textUtCellA2.Size = size;
			this.TextUtCellA.TabIndex = 59;
			this.Label32.AutoSize = true;
			this.Label32.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label35 = this.Label32;
			location = new global::System.Drawing.Point(409, 308);
			label35.Location = location;
			this.Label32.Name = "Label32";
			global::System.Windows.Forms.Control label36 = this.Label32;
			size = new global::System.Drawing.Size(87, 16);
			label36.Size = size;
			this.Label32.TabIndex = 58;
			this.Label32.Text = "Out Feeder A";
			this.TextUtRotation.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textUtRotation = this.TextUtRotation;
			location = new global::System.Drawing.Point(563, 277);
			textUtRotation.Location = location;
			this.TextUtRotation.Name = "TextUtRotation";
			this.TextUtRotation.ReadOnly = true;
			global::System.Windows.Forms.Control textUtRotation2 = this.TextUtRotation;
			size = new global::System.Drawing.Size(136, 22);
			textUtRotation2.Size = size;
			this.TextUtRotation.TabIndex = 57;
			this.Label33.AutoSize = true;
			this.Label33.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label37 = this.Label33;
			location = new global::System.Drawing.Point(409, 280);
			label37.Location = location;
			this.Label33.Name = "Label33";
			global::System.Windows.Forms.Control label38 = this.Label33;
			size = new global::System.Drawing.Size(81, 16);
			label38.Size = size;
			this.Label33.TabIndex = 56;
			this.Label33.Text = "Out Rotation";
			this.TextUtUppNer.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textUtUppNer = this.TextUtUppNer;
			location = new global::System.Drawing.Point(563, 233);
			textUtUppNer.Location = location;
			this.TextUtUppNer.Name = "TextUtUppNer";
			this.TextUtUppNer.ReadOnly = true;
			global::System.Windows.Forms.Control textUtUppNer2 = this.TextUtUppNer;
			size = new global::System.Drawing.Size(136, 22);
			textUtUppNer2.Size = size;
			this.TextUtUppNer.TabIndex = 55;
			this.Label34.AutoSize = true;
			this.Label34.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label39 = this.Label34;
			location = new global::System.Drawing.Point(409, 236);
			label39.Location = location;
			this.Label34.Name = "Label34";
			global::System.Windows.Forms.Control label40 = this.Label34;
			size = new global::System.Drawing.Size(82, 16);
			label40.Size = size;
			this.Label34.TabIndex = 54;
			this.Label34.Text = "Out up/down";
			this.TextINPotB.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textINPotB = this.TextINPotB;
			location = new global::System.Drawing.Point(563, 205);
			textINPotB.Location = location;
			this.TextINPotB.Name = "TextINPotB";
			this.TextINPotB.ReadOnly = true;
			global::System.Windows.Forms.Control textINPotB2 = this.TextINPotB;
			size = new global::System.Drawing.Size(136, 22);
			textINPotB2.Size = size;
			this.TextINPotB.TabIndex = 53;
			this.Label35.AutoSize = true;
			this.Label35.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label41 = this.Label35;
			location = new global::System.Drawing.Point(409, 208);
			label41.Location = location;
			this.Label35.Name = "Label35";
			global::System.Windows.Forms.Control label42 = this.Label35;
			size = new global::System.Drawing.Size(114, 16);
			label42.Size = size;
			this.Label35.TabIndex = 52;
			this.Label35.Text = "Potenitiometer (B)";
			this.TextInPotA.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textInPotA = this.TextInPotA;
			location = new global::System.Drawing.Point(563, 177);
			textInPotA.Location = location;
			this.TextInPotA.Name = "TextInPotA";
			this.TextInPotA.ReadOnly = true;
			global::System.Windows.Forms.Control textInPotA2 = this.TextInPotA;
			size = new global::System.Drawing.Size(136, 22);
			textInPotA2.Size = size;
			this.TextInPotA.TabIndex = 51;
			this.Label36.AutoSize = true;
			this.Label36.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label43 = this.Label36;
			location = new global::System.Drawing.Point(409, 180);
			label43.Location = location;
			this.Label36.Name = "Label36";
			global::System.Windows.Forms.Control label44 = this.Label36;
			size = new global::System.Drawing.Size(111, 16);
			label44.Size = size;
			this.Label36.TabIndex = 50;
			this.Label36.Text = "Potentiometer (A)";
			this.TextLuftFukt.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textLuftFukt = this.TextLuftFukt;
			location = new global::System.Drawing.Point(563, 149);
			textLuftFukt.Location = location;
			this.TextLuftFukt.Name = "TextLuftFukt";
			this.TextLuftFukt.ReadOnly = true;
			global::System.Windows.Forms.Control textLuftFukt2 = this.TextLuftFukt;
			size = new global::System.Drawing.Size(136, 22);
			textLuftFukt2.Size = size;
			this.TextLuftFukt.TabIndex = 49;
			this.Label37.AutoSize = true;
			this.Label37.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label45 = this.Label37;
			location = new global::System.Drawing.Point(409, 152);
			label45.Location = location;
			this.Label37.Name = "Label37";
			global::System.Windows.Forms.Control label46 = this.Label37;
			size = new global::System.Drawing.Size(102, 16);
			label46.Size = size;
			this.Label37.TabIndex = 48;
			this.Label37.Text = "Air Moist (RH%)";
			this.TextStatusAirValves.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textStatusAirValves = this.TextStatusAirValves;
			location = new global::System.Drawing.Point(563, 104);
			textStatusAirValves.Location = location;
			this.TextStatusAirValves.Name = "TextStatusAirValves";
			this.TextStatusAirValves.ReadOnly = true;
			global::System.Windows.Forms.Control textStatusAirValves2 = this.TextStatusAirValves;
			size = new global::System.Drawing.Size(136, 22);
			textStatusAirValves2.Size = size;
			this.TextStatusAirValves.TabIndex = 47;
			this.Label38.AutoSize = true;
			this.Label38.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label47 = this.Label38;
			location = new global::System.Drawing.Point(409, 107);
			label47.Location = location;
			this.Label38.Name = "Label38";
			global::System.Windows.Forms.Control label48 = this.Label38;
			size = new global::System.Drawing.Size(106, 16);
			label48.Size = size;
			this.Label38.TabIndex = 46;
			this.Label38.Text = "Status air valves";
			this.TextCarrier.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textCarrier = this.TextCarrier;
			location = new global::System.Drawing.Point(563, 76);
			textCarrier.Location = location;
			this.TextCarrier.Name = "TextCarrier";
			this.TextCarrier.ReadOnly = true;
			global::System.Windows.Forms.Control textCarrier2 = this.TextCarrier;
			size = new global::System.Drawing.Size(136, 22);
			textCarrier2.Size = size;
			this.TextCarrier.TabIndex = 45;
			this.Label39.AutoSize = true;
			this.Label39.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label49 = this.Label39;
			location = new global::System.Drawing.Point(409, 79);
			label49.Location = location;
			this.Label39.Name = "Label39";
			global::System.Windows.Forms.Control label50 = this.Label39;
			size = new global::System.Drawing.Size(74, 16);
			label50.Size = size;
			this.Label39.TabIndex = 44;
			this.Label39.Text = "Carrier (no)";
			this.TextInstaller.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textInstaller = this.TextInstaller;
			location = new global::System.Drawing.Point(563, 48);
			textInstaller.Location = location;
			this.TextInstaller.Name = "TextInstaller";
			this.TextInstaller.ReadOnly = true;
			global::System.Windows.Forms.Control textInstaller2 = this.TextInstaller;
			size = new global::System.Drawing.Size(136, 22);
			textInstaller2.Size = size;
			this.TextInstaller.TabIndex = 43;
			this.Label40.AutoSize = true;
			this.Label40.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label51 = this.Label40;
			location = new global::System.Drawing.Point(409, 51);
			label51.Location = location;
			this.Label40.Name = "Label40";
			global::System.Windows.Forms.Control label52 = this.Label40;
			size = new global::System.Drawing.Size(80, 16);
			label52.Size = size;
			this.Label40.TabIndex = 42;
			this.Label40.Text = "Installer (no)";
			this.Label22.AutoSize = true;
			this.Label22.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label53 = this.Label22;
			location = new global::System.Drawing.Point(22, 365);
			label53.Location = location;
			this.Label22.Name = "Label22";
			global::System.Windows.Forms.Control label54 = this.Label22;
			size = new global::System.Drawing.Size(105, 16);
			label54.Size = size;
			this.Label22.TabIndex = 38;
			this.Label22.Text = "Auger Depth (m)";
			this.TextKomprTemp.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textKomprTemp = this.TextKomprTemp;
			location = new global::System.Drawing.Point(176, 460);
			textKomprTemp.Location = location;
			this.TextKomprTemp.Name = "TextKomprTemp";
			this.TextKomprTemp.ReadOnly = true;
			global::System.Windows.Forms.Control textKomprTemp2 = this.TextKomprTemp;
			size = new global::System.Drawing.Size(136, 22);
			textKomprTemp2.Size = size;
			this.TextKomprTemp.TabIndex = 37;
			this.TextTankBTemp.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBTemp = this.TextTankBTemp;
			location = new global::System.Drawing.Point(176, 432);
			textTankBTemp.Location = location;
			this.TextTankBTemp.Name = "TextTankBTemp";
			this.TextTankBTemp.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBTemp2 = this.TextTankBTemp;
			size = new global::System.Drawing.Size(136, 22);
			textTankBTemp2.Size = size;
			this.TextTankBTemp.TabIndex = 35;
			this.Label24.AutoSize = true;
			this.Label24.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label55 = this.Label24;
			location = new global::System.Drawing.Point(22, 463);
			label55.Location = location;
			this.Label24.Name = "Label24";
			global::System.Windows.Forms.Control label56 = this.Label24;
			size = new global::System.Drawing.Size(122, 16);
			label56.Size = size;
			this.Label24.TabIndex = 34;
			this.Label24.Text = "Compr. Air Heat (C)";
			this.TextTankATemp.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankATemp = this.TextTankATemp;
			location = new global::System.Drawing.Point(176, 404);
			textTankATemp.Location = location;
			this.TextTankATemp.Name = "TextTankATemp";
			this.TextTankATemp.ReadOnly = true;
			global::System.Windows.Forms.Control textTankATemp2 = this.TextTankATemp;
			size = new global::System.Drawing.Size(136, 22);
			textTankATemp2.Size = size;
			this.TextTankATemp.TabIndex = 33;
			this.Label25.AutoSize = true;
			this.Label25.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label57 = this.Label25;
			location = new global::System.Drawing.Point(22, 435);
			label57.Location = location;
			this.Label25.Name = "Label25";
			global::System.Windows.Forms.Control label58 = this.Label25;
			size = new global::System.Drawing.Size(122, 16);
			label58.Size = size;
			this.Label25.TabIndex = 32;
			this.Label25.Text = "Tank B Air Heat (C)";
			this.TextBorrDjup.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textBorrDjup = this.TextBorrDjup;
			location = new global::System.Drawing.Point(176, 362);
			textBorrDjup.Location = location;
			this.TextBorrDjup.Name = "TextBorrDjup";
			this.TextBorrDjup.ReadOnly = true;
			global::System.Windows.Forms.Control textBorrDjup2 = this.TextBorrDjup;
			size = new global::System.Drawing.Size(136, 22);
			textBorrDjup2.Size = size;
			this.TextBorrDjup.TabIndex = 31;
			this.Label18.AutoSize = true;
			this.Label18.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label59 = this.Label18;
			location = new global::System.Drawing.Point(22, 407);
			label59.Location = location;
			this.Label18.Name = "Label18";
			global::System.Windows.Forms.Control label60 = this.Label18;
			size = new global::System.Drawing.Size(122, 16);
			label60.Size = size;
			this.Label18.TabIndex = 30;
			this.Label18.Text = "Tank A Air Heat (C)";
			this.TextCellBSpeed.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textCellBSpeed = this.TextCellBSpeed;
			location = new global::System.Drawing.Point(176, 334);
			textCellBSpeed.Location = location;
			this.TextCellBSpeed.Name = "TextCellBSpeed";
			this.TextCellBSpeed.ReadOnly = true;
			global::System.Windows.Forms.Control textCellBSpeed2 = this.TextCellBSpeed;
			size = new global::System.Drawing.Size(136, 22);
			textCellBSpeed2.Size = size;
			this.TextCellBSpeed.TabIndex = 29;
			this.Label19.AutoSize = true;
			this.Label19.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label61 = this.Label19;
			location = new global::System.Drawing.Point(22, 337);
			label61.Location = location;
			this.Label19.Name = "Label19";
			global::System.Windows.Forms.Control label62 = this.Label19;
			size = new global::System.Drawing.Size(119, 16);
			label62.Size = size;
			this.Label19.TabIndex = 28;
			this.Label19.Text = "Cell B speed (rpm)";
			this.TextCellASpeed.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textCellASpeed = this.TextCellASpeed;
			location = new global::System.Drawing.Point(176, 306);
			textCellASpeed.Location = location;
			this.TextCellASpeed.Name = "TextCellASpeed";
			this.TextCellASpeed.ReadOnly = true;
			global::System.Windows.Forms.Control textCellASpeed2 = this.TextCellASpeed;
			size = new global::System.Drawing.Size(136, 22);
			textCellASpeed2.Size = size;
			this.TextCellASpeed.TabIndex = 27;
			this.Label20.AutoSize = true;
			this.Label20.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label63 = this.Label20;
			location = new global::System.Drawing.Point(22, 309);
			label63.Location = location;
			this.Label20.Name = "Label20";
			global::System.Windows.Forms.Control label64 = this.Label20;
			size = new global::System.Drawing.Size(119, 16);
			label64.Size = size;
			this.Label20.TabIndex = 26;
			this.Label20.Text = "Cell A speed (rpm)";
			this.TextBorrSpeed.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textBorrSpeed = this.TextBorrSpeed;
			location = new global::System.Drawing.Point(176, 278);
			textBorrSpeed.Location = location;
			this.TextBorrSpeed.Name = "TextBorrSpeed";
			this.TextBorrSpeed.ReadOnly = true;
			global::System.Windows.Forms.Control textBorrSpeed2 = this.TextBorrSpeed;
			size = new global::System.Drawing.Size(136, 22);
			textBorrSpeed2.Size = size;
			this.TextBorrSpeed.TabIndex = 25;
			this.Label21.AutoSize = true;
			this.Label21.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label65 = this.Label21;
			location = new global::System.Drawing.Point(22, 281);
			label65.Location = location;
			this.Label21.Name = "Label21";
			global::System.Windows.Forms.Control label66 = this.Label21;
			size = new global::System.Drawing.Size(107, 16);
			label66.Size = size;
			this.Label21.TabIndex = 24;
			this.Label21.Text = "Drill speed (rpm)";
			this.TextTankBerror.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBerror = this.TextTankBerror;
			location = new global::System.Drawing.Point(563, 22);
			textTankBerror.Location = location;
			this.TextTankBerror.Name = "TextTankBerror";
			this.TextTankBerror.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBerror2 = this.TextTankBerror;
			size = new global::System.Drawing.Size(136, 22);
			textTankBerror2.Size = size;
			this.TextTankBerror.TabIndex = 23;
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label67 = this.Label14;
			location = new global::System.Drawing.Point(409, 25);
			label67.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label68 = this.Label14;
			size = new global::System.Drawing.Size(116, 16);
			label68.Size = size;
			this.Label14.TabIndex = 22;
			this.Label14.Text = "Tank B error code";
			this.TextTankBViktL.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBViktL = this.TextTankBViktL;
			location = new global::System.Drawing.Point(176, 206);
			textTankBViktL.Location = location;
			this.TextTankBViktL.Name = "TextTankBViktL";
			this.TextTankBViktL.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBViktL2 = this.TextTankBViktL;
			size = new global::System.Drawing.Size(136, 22);
			textTankBViktL2.Size = size;
			this.TextTankBViktL.TabIndex = 21;
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label69 = this.Label15;
			location = new global::System.Drawing.Point(22, 209);
			label69.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label70 = this.Label15;
			size = new global::System.Drawing.Size(127, 16);
			label70.Size = size;
			this.Label15.TabIndex = 20;
			this.Label15.Text = "Tank B Weight (low)";
			this.TextTankAError.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankAError = this.TextTankAError;
			location = new global::System.Drawing.Point(176, 487);
			textTankAError.Location = location;
			this.TextTankAError.Name = "TextTankAError";
			this.TextTankAError.ReadOnly = true;
			global::System.Windows.Forms.Control textTankAError2 = this.TextTankAError;
			size = new global::System.Drawing.Size(136, 22);
			textTankAError2.Size = size;
			this.TextTankAError.TabIndex = 19;
			this.Label16.AutoSize = true;
			this.Label16.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label71 = this.Label16;
			location = new global::System.Drawing.Point(22, 490);
			label71.Location = location;
			this.Label16.Name = "Label16";
			global::System.Windows.Forms.Control label72 = this.Label16;
			size = new global::System.Drawing.Size(116, 16);
			label72.Size = size;
			this.Label16.TabIndex = 18;
			this.Label16.Text = "Tank A error code";
			this.TextTankAViktL.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankAViktL = this.TextTankAViktL;
			location = new global::System.Drawing.Point(176, 150);
			textTankAViktL.Location = location;
			this.TextTankAViktL.Name = "TextTankAViktL";
			this.TextTankAViktL.ReadOnly = true;
			global::System.Windows.Forms.Control textTankAViktL2 = this.TextTankAViktL;
			size = new global::System.Drawing.Size(136, 22);
			textTankAViktL2.Size = size;
			this.TextTankAViktL.TabIndex = 17;
			this.Label17.AutoSize = true;
			this.Label17.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label73 = this.Label17;
			location = new global::System.Drawing.Point(22, 153);
			label73.Location = location;
			this.Label17.Name = "Label17";
			global::System.Windows.Forms.Control label74 = this.Label17;
			size = new global::System.Drawing.Size(127, 16);
			label74.Size = size;
			this.Label17.TabIndex = 16;
			this.Label17.Text = "Tank A Weight (low)";
			this.TextTankBTryck.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankBTryck = this.TextTankBTryck;
			location = new global::System.Drawing.Point(176, 105);
			textTankBTryck.Location = location;
			this.TextTankBTryck.Name = "TextTankBTryck";
			this.TextTankBTryck.ReadOnly = true;
			global::System.Windows.Forms.Control textTankBTryck2 = this.TextTankBTryck;
			size = new global::System.Drawing.Size(136, 22);
			textTankBTryck2.Size = size;
			this.TextTankBTryck.TabIndex = 15;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label75 = this.Label10;
			location = new global::System.Drawing.Point(22, 108);
			label75.Location = location;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label76 = this.Label10;
			size = new global::System.Drawing.Size(139, 16);
			label76.Size = size;
			this.Label10.TabIndex = 14;
			this.Label10.Text = "Tank B Pressure (bar)";
			this.TextTankATryck.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textTankATryck = this.TextTankATryck;
			location = new global::System.Drawing.Point(176, 77);
			textTankATryck.Location = location;
			this.TextTankATryck.Name = "TextTankATryck";
			this.TextTankATryck.ReadOnly = true;
			global::System.Windows.Forms.Control textTankATryck2 = this.TextTankATryck;
			size = new global::System.Drawing.Size(136, 22);
			textTankATryck2.Size = size;
			this.TextTankATryck.TabIndex = 13;
			this.Label11.AutoSize = true;
			this.Label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label77 = this.Label11;
			location = new global::System.Drawing.Point(22, 80);
			label77.Location = location;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label78 = this.Label11;
			size = new global::System.Drawing.Size(139, 16);
			label78.Size = size;
			this.Label11.TabIndex = 12;
			this.Label11.Text = "Tank A Pressure (bar)";
			this.TextSlangTryck.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textSlangTryck = this.TextSlangTryck;
			location = new global::System.Drawing.Point(176, 49);
			textSlangTryck.Location = location;
			this.TextSlangTryck.Name = "TextSlangTryck";
			this.TextSlangTryck.ReadOnly = true;
			global::System.Windows.Forms.Control textSlangTryck2 = this.TextSlangTryck;
			size = new global::System.Drawing.Size(136, 22);
			textSlangTryck2.Size = size;
			this.TextSlangTryck.TabIndex = 11;
			this.Label12.AutoSize = true;
			this.Label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label79 = this.Label12;
			location = new global::System.Drawing.Point(22, 52);
			label79.Location = location;
			this.Label12.Name = "Label12";
			global::System.Windows.Forms.Control label80 = this.Label12;
			size = new global::System.Drawing.Size(124, 16);
			label80.Size = size;
			this.Label12.TabIndex = 10;
			this.Label12.Text = "Pipe Pressure (bar)";
			this.TextSvivelTryck.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textSvivelTryck = this.TextSvivelTryck;
			location = new global::System.Drawing.Point(176, 22);
			textSvivelTryck.Location = location;
			this.TextSvivelTryck.Name = "TextSvivelTryck";
			this.TextSvivelTryck.ReadOnly = true;
			global::System.Windows.Forms.Control textSvivelTryck2 = this.TextSvivelTryck;
			size = new global::System.Drawing.Size(136, 22);
			textSvivelTryck2.Size = size;
			this.TextSvivelTryck.TabIndex = 9;
			this.Label13.AutoSize = true;
			this.Label13.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label81 = this.Label13;
			location = new global::System.Drawing.Point(22, 24);
			label81.Location = location;
			this.Label13.Name = "Label13";
			global::System.Windows.Forms.Control label82 = this.Label13;
			size = new global::System.Drawing.Size(133, 16);
			label82.Size = size;
			this.Label13.TabIndex = 8;
			this.Label13.Text = "Svivel Pressure (bar)";
			global::System.Windows.Forms.Control button = this.Button1;
			location = new global::System.Drawing.Point(731, 86);
			button.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button2 = this.Button1;
			size = new global::System.Drawing.Size(94, 45);
			button2.Size = size;
			this.Button1.TabIndex = 11;
			this.Button1.Text = "F6 = Show Settings";
			this.Button1.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control button3 = this.Button2;
			location = new global::System.Drawing.Point(731, 144);
			button3.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button4 = this.Button2;
			size = new global::System.Drawing.Size(94, 45);
			button4.Size = size;
			this.Button2.TabIndex = 12;
			this.Button2.Text = "F7 = Show Main Drill";
			this.Button2.UseVisualStyleBackColor = true;
			this.GroupBox1.Controls.Add(this.RadioDriver4);
			this.GroupBox1.Controls.Add(this.TextDriver4);
			this.GroupBox1.Controls.Add(this.RadioDriver3);
			this.GroupBox1.Controls.Add(this.TextDriver3);
			this.GroupBox1.Controls.Add(this.RadioDriver2);
			this.GroupBox1.Controls.Add(this.TextDriver2);
			this.GroupBox1.Controls.Add(this.RadioDriver1);
			this.GroupBox1.Controls.Add(this.TextDriver1);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			location = new global::System.Drawing.Point(373, 28);
			groupBox.Location = location;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(352, 171);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 13;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "Drivers";
			this.RadioDriver4.AutoSize = true;
			global::System.Windows.Forms.Control radioDriver = this.RadioDriver4;
			location = new global::System.Drawing.Point(25, 130);
			radioDriver.Location = location;
			this.RadioDriver4.Name = "RadioDriver4";
			global::System.Windows.Forms.Control radioDriver2 = this.RadioDriver4;
			size = new global::System.Drawing.Size(14, 13);
			radioDriver2.Size = size;
			this.RadioDriver4.TabIndex = 31;
			this.RadioDriver4.TabStop = true;
			this.RadioDriver4.UseVisualStyleBackColor = true;
			this.TextDriver4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textDriver = this.TextDriver4;
			location = new global::System.Drawing.Point(70, 127);
			textDriver.Location = location;
			this.TextDriver4.Name = "TextDriver4";
			global::System.Windows.Forms.Control textDriver2 = this.TextDriver4;
			size = new global::System.Drawing.Size(250, 22);
			textDriver2.Size = size;
			this.TextDriver4.TabIndex = 30;
			this.RadioDriver3.AutoSize = true;
			global::System.Windows.Forms.Control radioDriver3 = this.RadioDriver3;
			location = new global::System.Drawing.Point(25, 103);
			radioDriver3.Location = location;
			this.RadioDriver3.Name = "RadioDriver3";
			global::System.Windows.Forms.Control radioDriver4 = this.RadioDriver3;
			size = new global::System.Drawing.Size(14, 13);
			radioDriver4.Size = size;
			this.RadioDriver3.TabIndex = 29;
			this.RadioDriver3.TabStop = true;
			this.RadioDriver3.UseVisualStyleBackColor = true;
			this.TextDriver3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textDriver3 = this.TextDriver3;
			location = new global::System.Drawing.Point(70, 100);
			textDriver3.Location = location;
			this.TextDriver3.Name = "TextDriver3";
			global::System.Windows.Forms.Control textDriver4 = this.TextDriver3;
			size = new global::System.Drawing.Size(250, 22);
			textDriver4.Size = size;
			this.TextDriver3.TabIndex = 28;
			this.RadioDriver2.AutoSize = true;
			global::System.Windows.Forms.Control radioDriver5 = this.RadioDriver2;
			location = new global::System.Drawing.Point(25, 72);
			radioDriver5.Location = location;
			this.RadioDriver2.Name = "RadioDriver2";
			global::System.Windows.Forms.Control radioDriver6 = this.RadioDriver2;
			size = new global::System.Drawing.Size(14, 13);
			radioDriver6.Size = size;
			this.RadioDriver2.TabIndex = 27;
			this.RadioDriver2.TabStop = true;
			this.RadioDriver2.UseVisualStyleBackColor = true;
			this.TextDriver2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textDriver5 = this.TextDriver2;
			location = new global::System.Drawing.Point(70, 69);
			textDriver5.Location = location;
			this.TextDriver2.Name = "TextDriver2";
			global::System.Windows.Forms.Control textDriver6 = this.TextDriver2;
			size = new global::System.Drawing.Size(250, 22);
			textDriver6.Size = size;
			this.TextDriver2.TabIndex = 26;
			this.RadioDriver1.AutoSize = true;
			global::System.Windows.Forms.Control radioDriver7 = this.RadioDriver1;
			location = new global::System.Drawing.Point(25, 44);
			radioDriver7.Location = location;
			this.RadioDriver1.Name = "RadioDriver1";
			global::System.Windows.Forms.Control radioDriver8 = this.RadioDriver1;
			size = new global::System.Drawing.Size(14, 13);
			radioDriver8.Size = size;
			this.RadioDriver1.TabIndex = 25;
			this.RadioDriver1.TabStop = true;
			this.RadioDriver1.UseVisualStyleBackColor = true;
			this.TextDriver1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control textDriver7 = this.TextDriver1;
			location = new global::System.Drawing.Point(70, 41);
			textDriver7.Location = location;
			this.TextDriver1.Name = "TextDriver1";
			global::System.Windows.Forms.Control textDriver8 = this.TextDriver1;
			size = new global::System.Drawing.Size(250, 22);
			textDriver8.Size = size;
			this.TextDriver1.TabIndex = 24;
			this.chkNovatron.AutoSize = true;
			global::System.Windows.Forms.Control chkNovatron = this.chkNovatron;
			location = new global::System.Drawing.Point(563, 460);
			chkNovatron.Location = location;
			this.chkNovatron.Name = "chkNovatron";
			global::System.Windows.Forms.Control chkNovatron2 = this.chkNovatron;
			size = new global::System.Drawing.Size(64, 20);
			chkNovatron2.Size = size;
			this.chkNovatron.TabIndex = 76;
			this.chkNovatron.Text = "On/Off";
			this.chkNovatron.UseVisualStyleBackColor = true;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(884, 733);
			this.ClientSize = size;
			this.Controls.Add(this.GroupBox1);
			this.Controls.Add(this.Button2);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.GroupMätVärden);
			this.Controls.Add(this.Label5);
			this.Controls.Add(this.Label4);
			this.Controls.Add(this.Label3);
			this.Controls.Add(this.Label2);
			this.Controls.Add(this.GroupBoxStatus);
			this.KeyPreview = true;
			this.MinimizeBox = false;
			this.Name = "TestarKom";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Testar kommunikation med Festo";
			this.GroupBoxStatus.ResumeLayout(false);
			this.GroupBoxStatus.PerformLayout();
			this.GroupMätVärden.ResumeLayout(false);
			this.GroupMätVärden.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.NUpGround).EndInit();
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x04000110 RID: 272
		private global::System.ComponentModel.IContainer components;
	}
}
